alter table dbo.bitstream
Alter column contentType varchar(250)

if  exists (select bitstreamId from dbo.bitstream where ext='.doc' and contentType='')
Begin

update dbo.bitstream set contentType='video/x-ms-asf' where ext='.asf'
update dbo.bitstream set contentType='video/x-msvideo'  where ext='.avi'
update dbo.bitstream set contentType='image/bmp'  where ext='.bmp'
update dbo.bitstream set contentType='text/css' where ext='.css'
update dbo.bitstream set contentType='application/x-msdownload' where ext='.dll'
update dbo.bitstream set contentType='application/msword' where ext='.doc'
update dbo.bitstream set contentType='application/vnd.ms-word.document.macroEnabled.12' where ext='.docm'
update dbo.bitstream set contentType='application/vnd.openxmlformats-officedocument.wordprocessingml.document'  where ext='.docx'
update dbo.bitstream set contentType='application/msword' where ext='.dot'
update dbo.bitstream set contentType='drawing/x-dwg'  where ext='.dwg'
update dbo.bitstream set contentType='application/octet-stream' where ext='.exe'
update dbo.bitstream set contentType='application/octet-stream' where ext='.fla'
update dbo.bitstream set contentType='image/gif'  where ext='.gif'
update dbo.bitstream set contentType='text/html'  where ext='.html'
update dbo.bitstream set contentType='application/octet-stream' where ext='.INF'
update dbo.bitstream set contentType='application/octet-stream' where ext='.isf'
update dbo.bitstream set contentType='application/octet-stream' where ext='.java'
update dbo.bitstream set contentType='image/jpeg' where ext='.jpe'
update dbo.bitstream set contentType='image/jpeg' where ext='.jpeg'
update dbo.bitstream set contentType='image/jpeg' where ext='.jpg'
update dbo.bitstream set contentType='applicaton/x-msaccess'  where ext='.mdb'
update dbo.bitstream set contentType='message/rfc822' where ext='.mht'
update dbo.bitstream set contentType='application/octet-stream' where ext='.mix'
update dbo.bitstream set contentType='text/xml' where ext='.mno'
update dbo.bitstream set contentType='video/quicktime'  where ext='.MOV'
update dbo.bitstream set contentType='audio/mpeg' where ext='.mp3'
update dbo.bitstream set contentType='video/mpeg' where ext='.mpg'
update dbo.bitstream set contentType='applicaton/vnd.ms-project'  where ext='.MPP'
update dbo.bitstream set contentType='application/octet-stream' where ext='.msi'
update dbo.bitstream set contentType='applicaton/pdf' where ext='.pdf'
update dbo.bitstream set contentType='image/png'  where ext='.png'
update dbo.bitstream set contentType='application/vnd.ms-powerpoint'  where ext='.ppt'
update dbo.bitstream set contentType='application/octet-stream' where ext='.pptm'
update dbo.bitstream set contentType='application/vnd.openxmlformats-officedocument.presentationml.presentation'  where ext='.pptx'
update dbo.bitstream set contentType='application/octet-stream' where ext='.psd'
update dbo.bitstream set contentType='application/x-mspublisher'  where ext='.pub'
update dbo.bitstream set contentType='application/octet-stream' where ext='.rar'
update dbo.bitstream set contentType='application/rtf'  where ext='.rtf'
update dbo.bitstream set contentType='applicaton/x-shockwave-flash' where ext='.swf'
update dbo.bitstream set contentType='image/tiff' where ext='.tif'
update dbo.bitstream set contentType='text/plain' where ext='.txt'
update dbo.bitstream set contentType='audio/wav'  where ext='.wav'
update dbo.bitstream set contentType='audio/x-ms-wma' where ext='.wma'
update dbo.bitstream set contentType='video/x-ms-wmv' where ext='.wmv'
update dbo.bitstream set contentType='application/vnd.ms-excel' where ext='.xls'
update dbo.bitstream set contentType='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'  where ext='.xlsx'
update dbo.bitstream set contentType='text/xml' where ext='.xml'
update dbo.bitstream set contentType='application/x-zip-compressed' where ext='.zip'
update dbo.bitstream set contentType='text/html'  where ext='.htm'

END