TRUNCATE TABLE marprin
insert marPrin(rowNum, critNum, title) values(1,  1, rtrim ('II (1): The school leader provides a clear vision as to how instruction should be addressed in the school.                                                                                                                             '))
insert marPrin(rowNum, critNum, title) values(2,  2, rtrim ('IV (2): The school leader ensures that teachers have formal roles in the decision-making process regarding school initiatives.                                                                                                         '))
insert marPrin(rowNum, critNum, title) values(3,  3, rtrim ('IV (4): The school leader ensures that teachers and staff have formal ways to provide input regarding the optimal functioning of the school and delegates responsibilities appropriately.                                              '))
insert marPrin(rowNum, critNum, title) values(4,  4, rtrim ('V (1): The school administrator is recognized as the leader of the school who continually improves his or her professional practice.                                                                                                   '))
insert marPrin(rowNum, critNum, title) values(5,  5, rtrim ('V (2): The school leader has the trust of the faculty and staff that his or her actions are guided by what is best for all student populations.                                                                                        '))
insert marPrin(rowNum, critNum, title) values(6,  6, rtrim ('V (6): The school leader acknowledges the success of the whole school, as well as individuals within the school.                                                                                                                       '))
insert marPrin(rowNum, critNum, title) values(7,  1, rtrim ('V (3): The school leader ensures that faculty and staff perceive the school environment as safe and orderly.                                                                                                                           '))
insert marPrin(rowNum, critNum, title) values(8,  2, rtrim ('V (4): The school leader ensures that students, parents, and the community perceive the school environment as safe and orderly.                                                                                                        '))
insert marPrin(rowNum, critNum, title) values(9,  1, rtrim ('I (3): The school leader ensures that data are analyzed, interpreted, and used to regularly monitor progress toward school achievement goals.                                                                                          '))
insert marPrin(rowNum, critNum, title) values(10, 2, rtrim ('I (4): The school leader ensures that data are analyzed, interpreted, and used to regularly monitor  progress toward achievement goals for individual students.                                                                        '))
insert marPrin(rowNum, critNum, title) values(11, 1, rtrim ('III (1): The school leader ensures that the school curriculum and accompanying assessments adhere to state and district standards.                                                                                                     '))
insert marPrin(rowNum, critNum, title) values(12, 2, rtrim ('III (2): The school leader ensures that the school curriculum is focused enough that it can be adequately addressed in the time available to teachers.                                                                                 '))
insert marPrin(rowNum, critNum, title) values(13, 3, rtrim ('III (3): The school leader ensures that all students have the opportunity to learn the critical content of the curriculum.                                                                                                             '))
insert marPrin(rowNum, critNum, title) values(14, 4, rtrim ('IV (3): The school leader ensures that teacher teams and collaborative groups regularly interact to address common issues regarding curriculum, assessment, instruction, and the achievement of all students.                          '))
insert marPrin(rowNum, critNum, title) values(15, 1, rtrim ('II (2): The school leader effectively supports and retains teachers who continually enhance their pedagogical skills through reflection and professional growth plans.                                                                 '))
insert marPrin(rowNum, critNum, title) values(16, 2, rtrim ('II (3): The school leader is aware of predominant instructional practices throughout the school.                                                                                                                                       '))
insert marPrin(rowNum, critNum, title) values(17, 3, rtrim ('II (4): The school leader ensures that teachers are provided with clear, ongoing evaluations of their pedagogical strengths and weaknesses that are based on multiple sources of data and are consistent with student achievement data.'))
insert marPrin(rowNum, critNum, title) values(18, 4, rtrim ('IV (1): The school leader ensures that teachers have opportunities to observe and discuss effective teaching.                                                                                                                          '))
insert marPrin(rowNum, critNum, title) values(19, 1, rtrim ('II (5): The school leader ensures that teachers are provided with job-embedded professional development that is directly related to their instructional growth goals.                                                                  '))
insert marPrin(rowNum, critNum, title) values(20, 2, rtrim ('V (5): The school leader manages the fiscal, operational, and technological resources of the school in a way that focuses on effective instruction and the achievement of all students.                                                '))
insert marPrin(rowNum, critNum, title) values(21, 1, rtrim ('IV (5): The school leader ensures that students, parents, and community have formal ways to provide input regarding the optimal functioning of the school.                                                                             '))
insert marPrin(rowNum, critNum, title) values(22, 1, rtrim ('I (1): The school leader ensures clear and measureable goals are established and focused on critical needs regarding improving overall student achievement at the school level.                                                        '))
insert marPrin(rowNum, critNum, title) values(23, 2, rtrim ('I (2): The school leader ensures clear and measureable goals are established and focused on critical needs regarding improving achievement of individual students within the school.                                                   '))
insert marPrin(rowNum, critNum, title) values(24, 3, rtrim ('I (5): The school leader ensures that appropriate school-level and classroom-level programs and practices are in place to help all students meet individual achievement goals when data indicate interventions are needed.             '))

update marPrin set pl1=rtrim('The school leader attempts to ensure that a school-wide language or model of instruction is in place, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                                            ') where rownum=1
update marPrin set pl1=rtrim('The school leader attempts to ensure that formal processes are in place to collect data from all teachers regarding their preferences on specific decisions, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                     ') where rownum=2
update marPrin set pl1=rtrim('The school leader attempts to ensure that input is regularly collected from teachers and staff and appropriately delegates responsibilities, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                     ') where rownum=3
update marPrin set pl1=rtrim('The school leader attempts to engage in activities to improve his or her professional practices, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                                                 ') where rownum=4
update marPrin set pl1=rtrim('The school leader attempts to perform with integrity and the best interest of all students, but does so sporadically or inconsistently OR the school leader does not attempt to do so.                                                                                                                               ') where rownum=5
update marPrin set pl1=rtrim('The school leader attempts to acknowledge and celebrate the accomplishments of the school as a whole and the accomplishments of individuals within the school, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                   ') where rownum=6
update marPrin set pl1=rtrim('The school leader attempts to ensure that well-defined routines and procedures are in place that lead to orderly conduct, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                        ') where rownum=7
update marPrin set pl1=rtrim('The school leader ensures that rules and procedures are reviewed and updated as necessary to ensure a safe and orderly school environment and the perception of such by students, parents, and the community.                                                                                                        ') where rownum=8
update marPrin set pl1=rtrim('The school leader attempts to ensure that data are available for tracking overall student achievement, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                                           ') where rownum=9
update marPrin set pl1=rtrim('The school leader attempts to ensure that data are available for individual student achievement, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                                                 ') where rownum=10
update marPrin set pl1=rtrim('The school leader attempts to ensure that both the written curriculum and accompanying assessments adhere to state and district standards, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                       ') where rownum=11
update marPrin set pl1=rtrim('The school leader attempts to ensure that the written curriculum has been unpacked in such a manner that essential elements have been identified, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                ') where rownum=12
update marPrin set pl1=rtrim('The school leader attempts to ensure that all students have access to the courses and classes that directly address the essential elements of the curriculum, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                    ') where rownum=13
update marPrin set pl1=rtrim('The school leader attempts to ensure that formal teams or collaborative groups of teachers and other relevant staff meet regularly and have specific goals relative to curriculum, assessment, and instruction, but does not complete the task or does so partially OR the school leader does not attempt to do so.  ') where rownum=14
update marPrin set pl1=rtrim('The school leader attempts to ensure that teachers establish growth goals regarding their pedagogical skills and track their individual progress, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                ') where rownum=15
update marPrin set pl1=rtrim('The school leader attempts to ensure that information about predominant instructional strategies in the school is collected and regularly interacts with teachers about the effectiveness of these strategies, but does not complete the task or does so partially OR the school leader does not attempt to do so.   ') where rownum=16
update marPrin set pl1=rtrim('The school leader attempts to ensure that specific evaluation data are collected on each teacher regarding their pedagogical strengths and weaknesses and that these data are gathered from multiple sources, but does not complete the task or does so partially OR the school leader does not attempt to do so.    ') where rownum=17
update marPrin set pl1=rtrim('The school leader attempts to ensure that teachers have regular opportunities to interact regarding effective instructional practices and observe specific examples of effective teaching virtually or in-person, but does not complete the task or does so partially OR the school leader does not attempt to do so.') where rownum=18
update marPrin set pl1=rtrim('The school leader attempts to ensure that job-embedded professional development is provided to teachers that is directly related to their instructional growth goals, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                            ') where rownum=19
update marPrin set pl1=rtrim('The school leader attempts to manage the fiscal, operational, and technological resources necessary to support effective teaching, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                               ') where rownum=20
update marPrin set pl1=rtrim('The school leader attempts to ensure that input is regularly collected from students, parents, and community, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                                                    ') where rownum=21
update marPrin set pl1=rtrim('The school leader attempts to ensure clear, measurable goals with specific timelines focused on critical needs regarding improving student achievement are established at the school level but does not complete the task or does so partially OR the school leader does not attempt to do so.                       ') where rownum=22
update marPrin set pl1=rtrim('The school leader attempts to ensure that written achievement goals that are clear, measureable, and focused, are established for each student, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                  ') where rownum=23
update marPrin set pl1=rtrim('The school leader attempts to ensure that programs and practices are in place for individual students who are not making adequate progress, but does not complete the task or does so partially OR the school leader does not attempt to do so.                                                                      ') where rownum=24

update marPrin set pl2=rtrim('The school leader ensures that a school-wide language or model of instruction is in place.                                                                                                            ') where rownum=1
update marPrin set pl2=rtrim('For specific types of decisions, the school leader ensures that formal processes are in place to collect data from all teachers regarding their preferences.                                          ') where rownum=2
update marPrin set pl2=rtrim('The school leader ensures that input is regularly collected from teachers and staff and appropriately delegates responsibilities.                                                                     ') where rownum=3
update marPrin set pl2=rtrim('The school leader continually engages in activities to improve his or her professional practices.                                                                                                     ') where rownum=4
update marPrin set pl2=rtrim('The school leader performs with integrity and the best interest of all students.                                                                                                                      ') where rownum=5
update marPrin set pl2=rtrim('The school leader at the appropriate time acknowledges and celebrates the accomplishments of the school as a whole and the accomplishments of individuals within the school.                          ') where rownum=6
update marPrin set pl2=rtrim('The school leader ensures that well-defined routines and procedures are in place that lead to orderly conduct.                                                                                        ') where rownum=7
update marPrin set pl2=rtrim('The school leader ensures that well-defined routines and procedures are in place that lead to orderly conduct.                                                                                        ') where rownum=8
update marPrin set pl2=rtrim('The school leader regularly ensures that data are available for tracking overall student achievement.                                                                                                 ') where rownum=9
update marPrin set pl2=rtrim('The school leader ensures that data are available for individual student achievement.                                                                                                                 ') where rownum=10
update marPrin set pl2=rtrim('The school leader ensures that both the written curriculum and accompanying assessments adhere to state and district standards.                                                                       ') where rownum=11
update marPrin set pl2=rtrim('The school leader ensures that the written curriculum has been unpacked in such a manner that essential elements have been identified.                                                                ') where rownum=12
update marPrin set pl2=rtrim('The school leader ensures that all students have access to the courses and classes that directly address the essential elements of the curriculum.                                                    ') where rownum=13
update marPrin set pl2=rtrim('The school leader ensures that formal teams or collaborative groups of teachers and other relevant staff meet regularly and have specific goals relative to curriculum, assessment, and instruction.  ') where rownum=14
update marPrin set pl2=rtrim('The school leader ensures that teachers establish growth goals regarding their pedagogical skills and track their individual progress.                                                                ') where rownum=15
update marPrin set pl2=rtrim('The school leader ensures that information about predominant instructional strategies in the school is collected and regularly interacts with teachers about the effectiveness of these strategies.   ') where rownum=16
update marPrin set pl2=rtrim('The school leader ensures that specific evaluation data are collected on each teacher regarding their pedagogical strengths and weaknesses and that these data are gathered from multiple sources.    ') where rownum=17
update marPrin set pl2=rtrim('The school leader ensures that teachers have regular opportunities to interact regarding effective instructional practices and observe specific examples of effective teaching virtually or in-person.') where rownum=18
update marPrin set pl2=rtrim('The school leader ensures that job-embedded professional development that is directly related to their instructional growth goals is provided to teachers.                                            ') where rownum=19
update marPrin set pl2=rtrim('The school leader manages the fiscal, operational, and technological resources necessary to support effective teaching.                                                                               ') where rownum=20
update marPrin set pl2=rtrim('The school leader ensures that input is regularly collected from students, parents, and community.                                                                                                    ') where rownum=21
update marPrin set pl2=rtrim('The school leader ensures clear, measurable goals with specific timelines focused on critical needs regarding improving student achievement are established at the school level.                      ') where rownum=22
update marPrin set pl2=rtrim('The school leader ensures each student has written achievement goals that are clear, measurable and focused on appropriate needs.                                                                     ') where rownum=23
update marPrin set pl2=rtrim('The school leader ensures that programs and practices are in place for individual students who are not making adequate progress.                                                                      ') where rownum=24


update marPrin set pl3=rtrim('The school leader ensures that a school-wide language or model of instruction is in place AND monitors the extent to which the faculty and staff understands the instructional model.                                                                                                                                      ') where rownum=1
update marPrin set pl3=rtrim('For specific types of decisions, the school leader ensures that formal processes are in place to collect data from all teachers regarding their preferences AND monitors the extent to which those data are used to make decisions and the transparency of those decisions.                                                ') where rownum=2
update marPrin set pl3=rtrim('The school leader ensures that input is regularly collected from teachers and staff, appropriately delegates responsibilities, AND monitors the extent to which the inputs and delegations are contributing to the optimal function of the school.                                                                         ') where rownum=3
update marPrin set pl3=rtrim('The school leader continually engages in activities to improve his or her professional practices AND monitors the extent to which these activities enhance personal leadership skills and the staff’s confidence about his or her ability to lead.                                                                         ') where rownum=4
update marPrin set pl3=rtrim('The school leader performs with integrity and the best interest of all students AND monitors the extent to which faculty and staff perceive him or her as an individual who will follow through with initiatives and whose actions are guided by the desire to help all students learn.                                    ') where rownum=5
update marPrin set pl3=rtrim('The school leader at the appropriate time acknowledges and celebrates the accomplishments of the school as a whole and the accomplishments of individuals within the school AND monitors the extent to which people feel honored for their contributions.                                                                  ') where rownum=6
update marPrin set pl3=rtrim('The school leader ensures that well-defined routines and procedures are in place that lead to safe and orderly conduct AND monitors the extent to which faculty and staff share the perception that the school environment is safe and orderly.                                                                            ') where rownum=7
update marPrin set pl3=rtrim('The school leader ensures that well-defined routines and procedures are in place that lead to orderly conduct AND monitors the extent to which students, parents, and the community share the perception that the school environment is safe and orderly.                                                                  ') where rownum=8
update marPrin set pl3=rtrim('The school leader ensures that data are available for tracking overall student achievement AND monitors the extent to which student data are used to track progress toward goal.                                                                                                                                           ') where rownum=9
update marPrin set pl3=rtrim('The school leader ensures that data are available for individual student achievement AND monitors the extent to which data are used to t rack progress toward individual student goals.                                                                                                                                    ') where rownum=10
update marPrin set pl3=rtrim('The school leader ensures that both the written curriculum and accompanying assessments adhere to state and district standards AND monitors the extent to which the curriculum is delivered and the assessments properly administered.                                                                                     ') where rownum=11
update marPrin set pl3=rtrim('The school leader ensures that the written curriculum has been unpacked in such a manner that essential elements have been identified AND monitors the extent to which the essential elements are few enough to allow adequate time for students to learn them.                                                            ') where rownum=12
update marPrin set pl3=rtrim('The school leader ensures that all students have access to the courses and classes that directly address the essential elements of the curriculum AND monitors the extent to which those courses and classes utilize instructional strategies that most strongly increase their chances of learning the essential elements.') where rownum=13
update marPrin set pl3=rtrim('The school leader ensures that formal teams or collaborative groups of teachers and other relevant staff meet regularly and have specific goals relative to curriculum, assessment, and instruction AND monitors the extent to which these goals are designed to enhance the achievement of all students.                  ') where rownum=14
update marPrin set pl3=rtrim('The school leader ensures that teachers establish growth goals regarding their pedagogical skills and track their individual progress, AND monitors the extent to which teachers achieve their growth goals.                                                                                                               ') where rownum=15
update marPrin set pl3=rtrim('The school leader ensures that information about predominant instructional strategies in the school is collected, regularly interacts with teachers about the effectiveness of these strategies, AND monitors the extent to which the information is used to identify effective and ineffective practices.                 ') where rownum=16
update marPrin set pl3=rtrim('The school leader ensures that specific evaluation data are collected on each teacher regarding their pedagogical strengths and weaknesses and that these data are gathered from multiple sources AND monitors the extent to which teacher evaluations are consistent with student achievement data.                       ') where rownum=17
update marPrin set pl3=rtrim('The school leader ensures that teachers have regular opportunities to interact regarding effective instructional practices and observe specific examples of effective teaching virtually or in-person AND monitors the extent to which teachers actively participate in those opportunities.                               ') where rownum=18
update marPrin set pl3=rtrim('The school leader ensures that job-embedded professional development is provided to teachers that is directly related to their instructional growth goals AND monitors the extent to which teachers improve their instructional practices.                                                                                 ') where rownum=19
update marPrin set pl3=rtrim('The school leader manages the fiscal, operational, and technological resources necessary to support effective teaching AND monitors the extent to which the resources and efficiencies enhance instruction and the achievement of all students.                                                                            ') where rownum=20
update marPrin set pl3=rtrim('The school leader ensures that input is regularly collected from students, parents, and community AND monitors the extent to which the inputs are contributing to the optimal function of the school.                                                                                                                      ') where rownum=21
update marPrin set pl3=rtrim('The school leader ensures clear, measurable goals with specific timelines focused on critical needs regarding improving student achievement are established at the school level AND regularly monitors that everyone has understanding of the goals.                                                                       ') where rownum=22
update marPrin set pl3=rtrim('The school leader ensures each student has written achievement goals that are clear, measurable, and focused on appropriate needs AND regularly monitors teachers’ and their students’ understanding of individual student goals.                                                                                          ') where rownum=23
update marPrin set pl3=rtrim('The school leader ensures that programs and practices are in place for individual students who are not making adequate progress AND monitors whether students are successfully completing those programs.                                                                                                                  ') where rownum=24



update marPrin set pl4=rtrim('The school leader continually examines and makes adjustments so that all faculty and staff understand the nuances of the instructional model and integrates new instructional initiatives into the school instructional model.                                                          ') where rownum=1
update marPrin set pl4=rtrim('The school leader continually seeks new venues for teacher input regarding important decisions.                                                                                                                                                                                         ') where rownum=2
update marPrin set pl4=rtrim('The school leader intervenes and provides support when delegation of authority and teacher input is not working to optimize the function of the school.                                                                                                                                 ') where rownum=3
update marPrin set pl4=rtrim('The school leader actively seeks expertise/mentors for validation and feedback to confirm or improve leadership skills.                                                                                                                                                                 ') where rownum=4
update marPrin set pl4=rtrim('The school leader actively seeks expertise/mentors for validation and feedback to confirm or improve how he or she performs or is perceived.                                                                                                                                            ') where rownum=5
update marPrin set pl4=rtrim('The school leader actively seeks a variety of methods for acknowledging individual and school-wide success that meet the unique needs of faculty and staff.                                                                                                                             ') where rownum=6
update marPrin set pl4=rtrim('The school leader ensures that rules and procedures are reviewed and updated as necessary to ensure a safe and orderly school environment and the perception of such by school faculty and staff.                                                                                       ') where rownum=7
update marPrin set pl4=rtrim('The school leader ensures that rules and procedures are reviewed and updated as necessary to ensure a safe and orderly school environment and the perception of such by students, parents, and the community.                                                                           ') where rownum=8
update marPrin set pl4=rtrim('The school leader ensures that data are analyzed in a variety of ways to provide the most useful information and refines achievement goals or the tracking process as achievement data accrue.                                                                                          ') where rownum=9
update marPrin set pl4=rtrim('The school leader ensures that data are analyzed in a variety of ways to provide the most useful information and refines individual achievement goals or the tracking process as achievement data accrue.                                                                               ') where rownum=10
update marPrin set pl4=rtrim('The school leader ensures that the assessment and reporting system focuses on state and district standards and the leader intervenes with teachers who do not follow the state and district standards.                                                                                  ') where rownum=11
update marPrin set pl4=rtrim('The school leader ensures that essential elements of the curriculum are regularly examined and revised with an eye toward making instruction more focused and efficient.                                                                                                                ') where rownum=12
update marPrin set pl4=rtrim('The school leader intervenes with teachers whose students do not have adequate access to essential elements and instructional strategies that most strongly increase their chances of learning the essential elements.                                                                  ') where rownum=13
update marPrin set pl4=rtrim('The school leader ensures that group goals relative to curriculum, assessment, and instruction are regularly revised to reflect the changes in student achievement data and intervenes and supports teacher teams whose goals do not adequately address the achievement of all students.') where rownum=14
update marPrin set pl4=rtrim('The school leader regularly intervenes with and supports teachers who are not meeting their growth goals or adequately enhancing the achievement of their students.                                                                                                                     ') where rownum=15
update marPrin set pl4=rtrim('The school leader regularly intervenes to ensure that ineffective instructional practices are corrected and effective instructional practices are proliferating.                                                                                                                        ') where rownum=16
update marPrin set pl4=rtrim('The school leader ensures that teacher evaluation processes are updated regularly to ensure the results are consistent with student achievement data.                                                                                                                                   ') where rownum=17
update marPrin set pl4=rtrim('The school leader intervenes and supports teachers who do not actively participate in opportunities to interact regarding effective instructional practices.                                                                                                                            ') where rownum=18
update marPrin set pl4=rtrim('The school leader continually re-evaluates the professional development program to ensure that it remains job-embedded and focused on instructional growth goals and intervenes with teachers who are not making sufficient progress toward achieving growth goals.                     ') where rownum=19
update marPrin set pl4=rtrim('The school leader actively seeks and procures extra resources to enhance instruction and the achievement of all students.                                                                                                                                                               ') where rownum=20
update marPrin set pl4=rtrim('The school leader intervenes and provides support when students, parents, and community input is not working to optimize the function of the school.                                                                                                                                    ') where rownum=21
update marPrin set pl4=rtrim('The school leader ensures adjustments are made or new methods are utilized so that all stakeholders sufficiently understand the goals.                                                                                                                                                  ') where rownum=22
update marPrin set pl4=rtrim('The school leader ensures adjustments are made or new methods are utilized so that all faculty and students sufficiently understand the goals.                                                                                                                                          ') where rownum=23
update marPrin set pl4=rtrim('The school leader continually examines and expands the options for individual students to make adequate progress.                                                                                                                                                                       ') where rownum=24
