--Kennewick Principal State view
DECLARE @stateFramework  bigint, @fnDestBase bigint, @sourceFramework bigint
select @stateFramework = 19, @sourceFramework = 5
select @fnDestBase = MAX(frameworkNodeID) from SEFrameworkNode

insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C1','C1','Centering instruction on high expectations for student achievement',1,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C2','C2','Demonstrating effective teaching practices',2,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C3','C3','Recognizing individual student learning needs and developing strategies to address those needs',3,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C4','C4','Providing clear and intentional focus on subject matter content and curriculum',4,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C5','C5','Fostering and managing a safe, positive leaning environment',5,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C6','C6','Using multiple student data elements to modify instruction and improve student learning',6,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C7','C7','Communicating with parents and school community',7,1)
insert seframeworknode (frameworkId, parentNodeID, title, shortname, description, sequence, isLeafnode)values (@stateFramework, null, 'C8','C8','Exhibiting collaborative and collegial practices focus on improving instructional practice and student learning',8,1)

insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 84 , 10 ) --Recognize and Celebrate Efforts and Achievements                                                                                                                        
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 85 , 20 ) --Develops a Shared Vision, Values and Goals that Create School Identity                                                                                                  
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 86 , 30 ) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 87 , 40 ) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 88 , 50 ) --Develops and Models an Atmosphere of Personal Responsibility, Trust and Collaboration Among Students and Staff                                                          
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 1, 89 , 60 ) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 90 , 70 ) --Reviews, Analyzes and Implements a School Safety Plan                                                                                                                   
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 91 , 80 ) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 92 , 90 ) --Reviews Analyzes and Implements a School Discipline Plan                                                                                                                
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 93 , 100) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 94 , 110) --Supervises Teacher Classroom Management and Discipline                                                                                                                  
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 95 , 120) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 96 , 130) --Ensures that proper prevention and training (from Wenatchee)                                                                                                            
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 2, 97 , 140) --Ensures maintenance of physical plant (Wenatchee)                                                                                                                       
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 98 , 150) --Monitors, Assists and Evaluates Effective Instructional Practices                                                                                                       
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 99 , 160) --<span style="font-size: 13px; font-family: arialroundedmtbold;">  <p style="text-align: left;">Examples of Evidence &amp; Measures</p>  </span>                         
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 100, 170) --Monitors, Assists and Evaluates Effective Assessment Practices                                                                                                          
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 101, 180) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 102, 190) --Observes Instruction and Provides Feedback **Uses a variety of measures and methods for observations** (from Wenatchee) Uses a variety of data to monitor and improve in
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 103, 200) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 104, 210) --Assists Instructional Staff with the Alignment of Curriculum                                                                                                            
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 105, 220) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 106, 230) --Focus Staff on Teaching and Learning Priorities                                                                                                                         
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 107, 240) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 108, 250) --Develops School Performance Expectations (State &amp; Local Standards)                                                                                                  
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 5, 109, 260) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 110, 270) --Manages Human Resources To Support Student Achievement                                                                                                                  
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 111, 280) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 112, 290) --Plans Staff Development To Support Student Achievement                                                                                                                  
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 113, 300) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 114, 310) --Manages Financial Resources To Support Student Achievement and Legal Responsibilities                                                                                   
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 115, 320) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 116, 330) --Allocates Staffing Resources to Support Student Achievement                                                                                                             
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 117, 340) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 118, 350) --Managing Hiring Practices to Support Student Achievement and Legal Responsibilities                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 6, 119, 360) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 3, 120, 370) --Ensures the Development and Implementation of a Comprehensive School Improvement Plan                                                                                   
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 3, 121, 380) --Examples of Evidence &amp; Measures *** align to district plan *** (from Wenatchee)                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 3, 122, 390) --Utilizes a Variety of Data to Evaluate School Improvement Plan                                                                                                          
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 3, 123, 400) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 124, 410) --Communicates with School Community to Promote Student Learning                                                                                                          
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 125, 420) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 126, 430) --Partners with Community to Promote Student Learning                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 127, 440) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 128, 450) --Trains Staff in Utilizing Communication Tools with the School Community to Promote Student Learning                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 7, 129, 460) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 130, 470) --Understands the Achievement Gap                                                                                                                                         
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 131, 480) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 132, 490) --Leads Development of Plans to Address the Achievement Gap                                                                                                               
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 133, 500) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 134, 510) --Leads Actions To Address the Achievement Gap                                                                                                                            
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 135, 520) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 136, 530) --Supervises Teacher Instructional Practice To Ensure Equity For Students                                                                                                 
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 137, 540) --Examples of Evidence &amp; Measures                                                                                                                                     
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 138, 550) --Promote Equity and Access to All Students; THIS IS A SYSTEM RESPONSE                                                                                                    
insert seRubricRowFrameworkNode (frameworkNodeId, rubricRowID, sequence) values (@fnDestBase + 8, 139, 560) --Examples of Evidence &amp; Measures                                                                                                                                     
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
