//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientApp
    {
        public ClientApp()
        {
            this.RefreshTokens = new HashSet<RefreshToken>();
        }
    
        public string ClientAppId { get; set; }
        public string Secret { get; set; }
        public string Name { get; set; }
        public Nullable<short> ClientAppType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> RefreshTokenLifeTime { get; set; }
        public string AllowedOrigin { get; set; }
    
        public virtual ICollection<RefreshToken> RefreshTokens { get; set; }
    }
}
