//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDSError
    {
        public Nullable<long> stagingId { get; set; }
        public Nullable<long> personID { get; set; }
        public string locationCode { get; set; }
        public string locationName { get; set; }
        public string roleString { get; set; }
        public string rawRoleString { get; set; }
        public string districtCode { get; set; }
        public string schoolCode { get; set; }
        public Nullable<short> seEvaluationTypeID { get; set; }
        public string cAspnetUsers { get; set; }
        public string cAspnetUIR { get; set; }
        public string cInsertEval { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<bool> firstEntry { get; set; }
        public string errorMsg { get; set; }
        public string PrevousPersonId { get; set; }
        public long EDSErrorID { get; set; }
    }
}
