//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDSRolesV1
    {
        public Nullable<long> PersonId { get; set; }
        public string OrganizationName { get; set; }
        public string OSPILegacyCode { get; set; }
        public string OrganizationRoleName { get; set; }
        public long EDSRolesID { get; set; }
    }
}
