//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDSUsersV1
    {
        public Nullable<long> PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PreviousPersonId { get; set; }
        public string LoginName { get; set; }
        public string EmailAddressAlternate { get; set; }
        public string CertificateNumber { get; set; }
        public long EDSUsersID { get; set; }
    }
}
