//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationRoleClaim
    {
        public long LocationRoleClaimID { get; set; }
        public string userName { get; set; }
        public string LocationRoleClaim1 { get; set; }
        public string Location { get; set; }
        public string LocationCode { get; set; }
        public string RoleString { get; set; }
    }
}
