//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTypeRecipientConfig
    {
        public long MessageTypeRecipientConfigID { get; set; }
        public long RecipientID { get; set; }
        public int MessageTypeID { get; set; }
        public bool Inbox { get; set; }
        public Nullable<short> EmailDeliveryTypeID { get; set; }
    
        public virtual MessageType MessageType { get; set; }
    }
}
