//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtoFrameworksToLoad
    {
        public string dest { get; set; }
        public string src { get; set; }
        public string PlaceName { get; set; }
        public int SchoolYear { get; set; }
        public Nullable<int> nTeachers { get; set; }
    }
}
