//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAlignedEvidence
    {
        public long AlignedEvidenceID { get; set; }
        public long AvailableEvidenceID { get; set; }
        public short EvidenceTypeID { get; set; }
        public string AdditionalInput { get; set; }
        public long RubricRowEvaluationID { get; set; }
    
        public virtual SEAvailableEvidence SEAvailableEvidence { get; set; }
        public virtual SEEvidenceType SEEvidenceType { get; set; }
        public virtual SERubricRowEvaluation SERubricRowEvaluation { get; set; }
    }
}
