//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEAnchorType
    {
        public SEAnchorType()
        {
            this.SEEvalSessions = new HashSet<SEEvalSession>();
        }
    
        public short AnchorTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
    }
}
