//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEArtifactLibItem
    {
        public SEArtifactLibItem()
        {
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
        }
    
        public long ArtifactLibItemID { get; set; }
        public short ItemTypeID { get; set; }
        public Nullable<System.Guid> FileUUID { get; set; }
        public string WebUrl { get; set; }
        public string ProfPracticeNotes { get; set; }
        public long EvaluationID { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string FileName { get; set; }
        public long CreatedByUserID { get; set; }
    
        public virtual SEArtifactLibItemType SEArtifactLibItemType { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
