//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEArtifactBundleRejectionType
    {
        public SEArtifactBundleRejectionType()
        {
            this.SEArtifactBundleRejections = new HashSet<SEArtifactBundleRejection>();
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
        }
    
        public short ArtifactBundleRejectionTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEArtifactBundleRejection> SEArtifactBundleRejections { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
    }
}
