//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEArtifactBundle
    {
        public SEArtifactBundle()
        {
            this.SEArtifactBundleRejections = new HashSet<SEArtifactBundleRejection>();
            this.SEArtifactBundleWfHistories = new HashSet<SEArtifactBundleWfHistory>();
            this.SERubricRowAnnotations = new HashSet<SERubricRowAnnotation>();
            this.SEStudentGrowthGoals = new HashSet<SEStudentGrowthGoal>();
            this.SEArtifactLibItems = new HashSet<SEArtifactLibItem>();
            this.SERubricRows = new HashSet<SERubricRow>();
            this.SEStudentGrowthGoalBundles = new HashSet<SEStudentGrowthGoalBundle>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
            this.SEAvailableEvidences = new HashSet<SEAvailableEvidence>();
        }
    
        public long ArtifactBundleID { get; set; }
        public long EvaluationID { get; set; }
        public string Title { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string Context { get; set; }
        public string Evidence { get; set; }
        public long WfStateID { get; set; }
        public Nullable<System.DateTime> SubmitDateTime { get; set; }
        public Nullable<System.DateTime> RejectDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public Nullable<short> RejectionTypeID { get; set; }
        public string ShortName { get; set; }
    
        public virtual SEArtifactBundleRejectionType SEArtifactBundleRejectionType { get; set; }
        public virtual SEEvaluation SEEvaluation { get; set; }
        public virtual SEWfState SEWfState { get; set; }
        public virtual ICollection<SEArtifactBundleRejection> SEArtifactBundleRejections { get; set; }
        public virtual ICollection<SEArtifactBundleWfHistory> SEArtifactBundleWfHistories { get; set; }
        public virtual ICollection<SERubricRowAnnotation> SERubricRowAnnotations { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals { get; set; }
        public virtual ICollection<SEArtifactLibItem> SEArtifactLibItems { get; set; }
        public virtual ICollection<SERubricRow> SERubricRows { get; set; }
        public virtual ICollection<SEStudentGrowthGoalBundle> SEStudentGrowthGoalBundles { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
        public virtual ICollection<SEAvailableEvidence> SEAvailableEvidences { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
