//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEArtifactBundleWfHistory
    {
        public long ArtifactBundleWfHistoryID { get; set; }
        public long ArtifactBundleID { get; set; }
        public long TransitionID { get; set; }
        public string Comments { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual SEArtifactBundle SEArtifactBundle { get; set; }
    }
}
