//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEArtifactBundleRejection
    {
        public long ArtifactBundleRejectionID { get; set; }
        public long ArtifactBundleID { get; set; }
        public short RejectionTypeID { get; set; }
        public System.Guid CommunicationSessionKey { get; set; }
        public long CreatedByUserID { get; set; }
    
        public virtual SEArtifactBundleRejectionType SEArtifactBundleRejectionType { get; set; }
        public virtual SEArtifactBundle SEArtifactBundle { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
