//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDistrictTrainingProtocolAnchor
    {
        public long DistrictTrainingProtocolAnchorID { get; set; }
        public string DistrictCode { get; set; }
        public long TrainingProtocolID { get; set; }
        public long EvalSessionID { get; set; }
        public short SchoolYear { get; set; }
    
        public virtual SETrainingProtocol SETrainingProtocol { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
    }
}
