//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDistrictConfiguration
    {
        public long DistrictConfigurationID { get; set; }
        public long FrameworkContextID { get; set; }
        public string FinalReportTitle { get; set; }
        public string ObservationReportTitle { get; set; }
        public string SelfAssessReportTitle { get; set; }
        public Nullable<bool> StatementOfPerformanceIsRequired { get; set; }
        public Nullable<bool> NextYearEvalCycleIsRequired { get; set; }
        public Nullable<long> StudentGrowthGoalSetupWfStateID { get; set; }
    
        public virtual SEFrameworkContext SEFrameworkContext { get; set; }
    }
}
