//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDistrictPRViewing
    {
        public long DistrictUserID { get; set; }
        public string SchoolCode { get; set; }
        public short SchoolYear { get; set; }
    
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
