//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvaluationType
    {
        public SEEvaluationType()
        {
            this.SEUserPrompts = new HashSet<SEUserPrompt>();
            this.SEStudentGrowthProcessSettings = new HashSet<SEStudentGrowthProcessSetting>();
            this.SEEvaluations = new HashSet<SEEvaluation>();
            this.SEStudentGrowthFormPromptFrameworkNodes = new HashSet<SEStudentGrowthFormPromptFrameworkNode>();
            this.SESelfAssessments = new HashSet<SESelfAssessment>();
        }
    
        public short EvaluationTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEUserPrompt> SEUserPrompts { get; set; }
        public virtual ICollection<SEStudentGrowthProcessSetting> SEStudentGrowthProcessSettings { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations { get; set; }
        public virtual ICollection<SEStudentGrowthFormPromptFrameworkNode> SEStudentGrowthFormPromptFrameworkNodes { get; set; }
        public virtual ICollection<SESelfAssessment> SESelfAssessments { get; set; }
    }
}
