//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvent
    {
        public SEEvent()
        {
            this.SENotifications = new HashSet<SENotification>();
        }
    
        public long EventId { get; set; }
        public int EventTypeId { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string Url { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Note { get; set; }
        public Nullable<long> ObjectId { get; set; }
    
        public virtual SEEventType SEEventType { get; set; }
        public virtual ICollection<SENotification> SENotifications { get; set; }
    }
}
