//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvidenceType
    {
        public SEEvidenceType()
        {
            this.SEAvailableEvidences = new HashSet<SEAvailableEvidence>();
            this.SEAlignedEvidences = new HashSet<SEAlignedEvidence>();
        }
    
        public short EvidenceTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEAvailableEvidence> SEAvailableEvidences { get; set; }
        public virtual ICollection<SEAlignedEvidence> SEAlignedEvidences { get; set; }
    }
}
