//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvidenceCollection
    {
        public SEEvidenceCollection()
        {
            this.SEEvidenceCollectionRubricRowScores = new HashSet<SEEvidenceCollectionRubricRowScore>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
            this.SEAvailableEvidences = new HashSet<SEAvailableEvidence>();
        }
    
        public long EvidenceCollectionID { get; set; }
        public short EvidenceCollectionTypeID { get; set; }
        public Nullable<long> CollectionObjectID { get; set; }
        public Nullable<short> PerformanceLevel { get; set; }
        public long EvaluationID { get; set; }
    
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel { get; set; }
        public virtual ICollection<SEEvidenceCollectionRubricRowScore> SEEvidenceCollectionRubricRowScores { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
        public virtual SEEvidenceCollectionType SEEvidenceCollectionType { get; set; }
        public virtual ICollection<SEAvailableEvidence> SEAvailableEvidences { get; set; }
        public virtual SEEvaluation SEEvaluation { get; set; }
        public virtual SEEvaluation SEEvaluation1 { get; set; }
    }
}
