//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvalAssignmentRequest
    {
        public long EvalAssignmentRequestID { get; set; }
        public long EvaluateeID { get; set; }
        public long EvaluatorID { get; set; }
        public short RequestTypeID { get; set; }
        public short Status { get; set; }
        public short SchoolYear { get; set; }
        public string DistrictCode { get; set; }
    
        public virtual SEEvalAssignmentRequestStatusType SEEvalAssignmentRequestStatusType { get; set; }
        public virtual SEEvalAssignmentRequestType SEEvalAssignmentRequestType { get; set; }
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEUser SEUser1 { get; set; }
    }
}
