//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEvalAssignmentRequestType
    {
        public SEEvalAssignmentRequestType()
        {
            this.SEEvalAssignmentRequests = new HashSet<SEEvalAssignmentRequest>();
        }
    
        public short EvalAssignmentRequestTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEEvalAssignmentRequest> SEEvalAssignmentRequests { get; set; }
    }
}
