//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEEventType
    {
        public SEEventType()
        {
            this.SEEvents = new HashSet<SEEvent>();
            this.EventTypeEmailRecipientConfigs = new HashSet<EventTypeEmailRecipientConfig>();
        }
    
        public int EventTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SEEvent> SEEvents { get; set; }
        public virtual ICollection<EventTypeEmailRecipientConfig> EventTypeEmailRecipientConfigs { get; set; }
    }
}
