//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEFrameworkType
    {
        public SEFrameworkType()
        {
            this.SEFrameworks = new HashSet<SEFramework>();
        }
    
        public short FrameworkTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short RubricPL1ID { get; set; }
        public short RubricPL2ID { get; set; }
        public short RubricPL3ID { get; set; }
        public short RubricPL4ID { get; set; }
        public bool IsStateFramework { get; set; }
        public bool IsPrincipalEval { get; set; }
    
        public virtual ICollection<SEFramework> SEFrameworks { get; set; }
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel { get; set; }
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel1 { get; set; }
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel2 { get; set; }
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel3 { get; set; }
    }
}
