//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEFrameworkNode
    {
        public SEFrameworkNode()
        {
            this.SEFrameworkNode1 = new HashSet<SEFrameworkNode>();
            this.SEPullQuotes = new HashSet<SEPullQuote>();
            this.SERubricRowFrameworkNodes = new HashSet<SERubricRowFrameworkNode>();
            this.SETrainingProtocolFrameworkNodeAlignments = new HashSet<SETrainingProtocolFrameworkNodeAlignment>();
            this.SEStudentGrowthGoals = new HashSet<SEStudentGrowthGoal>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
            this.SEEvalSessions1 = new HashSet<SEEvalSession>();
            this.SEEvaluations = new HashSet<SEEvaluation>();
            this.SEEvaluations1 = new HashSet<SEEvaluation>();
            this.SEEvaluations2 = new HashSet<SEEvaluation>();
            this.SEEvaluations3 = new HashSet<SEEvaluation>();
            this.SESummativeFrameworkNodeScores = new HashSet<SESummativeFrameworkNodeScore>();
            this.SEStudentGrowthFormPromptFrameworkNodes = new HashSet<SEStudentGrowthFormPromptFrameworkNode>();
            this.SEFrameworkNodeScores = new HashSet<SEFrameworkNodeScore>();
        }
    
        public long FrameworkNodeID { get; set; }
        public long FrameworkID { get; set; }
        public Nullable<long> ParentNodeID { get; set; }
        public string Title { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public bool IsStateFramework { get; set; }
        public short Sequence { get; set; }
        public bool IsLeafNode { get; set; }
        public Nullable<System.Guid> XferID { get; set; }
        public Nullable<System.Guid> StickyID { get; set; }
    
        public virtual ICollection<SEFrameworkNode> SEFrameworkNode1 { get; set; }
        public virtual SEFrameworkNode SEFrameworkNode2 { get; set; }
        public virtual ICollection<SEPullQuote> SEPullQuotes { get; set; }
        public virtual ICollection<SERubricRowFrameworkNode> SERubricRowFrameworkNodes { get; set; }
        public virtual ICollection<SETrainingProtocolFrameworkNodeAlignment> SETrainingProtocolFrameworkNodeAlignments { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals { get; set; }
        public virtual SEFramework SEFramework { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions1 { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations1 { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations2 { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations3 { get; set; }
        public virtual ICollection<SESummativeFrameworkNodeScore> SESummativeFrameworkNodeScores { get; set; }
        public virtual ICollection<SEStudentGrowthFormPromptFrameworkNode> SEStudentGrowthFormPromptFrameworkNodes { get; set; }
        public virtual ICollection<SEFrameworkNodeScore> SEFrameworkNodeScores { get; set; }
    }
}
