//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEFrameworkContext
    {
        public SEFrameworkContext()
        {
            this.SEDistrictConfigurations = new HashSet<SEDistrictConfiguration>();
            this.SEFrameworks = new HashSet<SEFramework>();
        }
    
        public long FrameworkContextID { get; set; }
        public string Name { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<long> StateFrameworkID { get; set; }
        public Nullable<long> InstructionalFrameworkID { get; set; }
        public short EvaluationTypeID { get; set; }
        public short SchoolYear { get; set; }
        public Nullable<System.DateTime> LoadDateTime { get; set; }
        public bool IsActive { get; set; }
        public long PrototypeFrameworkContextID { get; set; }
        public Nullable<short> FrameworkViewTypeID { get; set; }
    
        public virtual ICollection<SEDistrictConfiguration> SEDistrictConfigurations { get; set; }
        public virtual ICollection<SEFramework> SEFrameworks { get; set; }
    }
}
