//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEFramework
    {
        public SEFramework()
        {
            this.SEFrameworkNodes = new HashSet<SEFrameworkNode>();
            this.SEFrameworkPerformanceLevels = new HashSet<SEFrameworkPerformanceLevel>();
        }
    
        public long FrameworkID { get; set; }
        public string Name { get; set; }
        public long FrameworkContextID { get; set; }
        public long PrototypeFrameworkID { get; set; }
        public Nullable<System.Guid> XferId { get; set; }
        public Nullable<System.Guid> StickyID { get; set; }
    
        public virtual SEFrameworkContext SEFrameworkContext { get; set; }
        public virtual ICollection<SEFrameworkNode> SEFrameworkNodes { get; set; }
        public virtual ICollection<SEFrameworkPerformanceLevel> SEFrameworkPerformanceLevels { get; set; }
    }
}
