//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELearningWalkSessionScore
    {
        public long LearningWalkSessionScoreID { get; set; }
        public long ClassroomID { get; set; }
        public long EvalSessionID { get; set; }
        public short PerformanceLevelID { get; set; }
        public long SEUserID { get; set; }
    
        public virtual SELearningWalkClassRoom SELearningWalkClassRoom { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SERubricPerformanceLevel SERubricPerformanceLevel { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
    }
}
