//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELearningWalkClassroomLabel
    {
        public SELearningWalkClassroomLabel()
        {
            this.SELearningWalkClassRooms = new HashSet<SELearningWalkClassRoom>();
        }
    
        public long LabelID { get; set; }
        public string Label { get; set; }
        public long PracticeSessionID { get; set; }
    
        public virtual ICollection<SELearningWalkClassRoom> SELearningWalkClassRooms { get; set; }
        public virtual SEPracticeSession SEPracticeSession { get; set; }
    }
}
