//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELearningWalkClassRoom
    {
        public SELearningWalkClassRoom()
        {
            this.SELearningWalkSessionScores = new HashSet<SELearningWalkSessionScore>();
            this.SELearningWalkClassroomLabels = new HashSet<SELearningWalkClassroomLabel>();
            this.SEFrameworkNodeScores = new HashSet<SEFrameworkNodeScore>();
            this.SERubricRowScores = new HashSet<SERubricRowScore>();
        }
    
        public long LearningWalkClassRoomID { get; set; }
        public long PracticeSessionID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SELearningWalkSessionScore> SELearningWalkSessionScores { get; set; }
        public virtual ICollection<SELearningWalkClassroomLabel> SELearningWalkClassroomLabels { get; set; }
        public virtual SEPracticeSession SEPracticeSession { get; set; }
        public virtual ICollection<SEFrameworkNodeScore> SEFrameworkNodeScores { get; set; }
        public virtual ICollection<SERubricRowScore> SERubricRowScores { get; set; }
    }
}
