//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENotification
    {
        public long NotificationId { get; set; }
        public Nullable<long> EventId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> ReceiverUserId { get; set; }
        public Nullable<int> ReceiverRoleId { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public string AlignedTo { get; set; }
        public Nullable<System.DateTime> ViewedDateTime { get; set; }
        public Nullable<bool> EmailSentForNotification { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
    
        public virtual SEEvent SEEvent { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEUser SEUser1 { get; set; }
    }
}
