//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPracticeSession
    {
        public SEPracticeSession()
        {
            this.SELearningWalkClassRooms = new HashSet<SELearningWalkClassRoom>();
            this.SELearningWalkClassroomLabels = new HashSet<SELearningWalkClassroomLabel>();
            this.SEPracticeSessionParticipants = new HashSet<SEPracticeSessionParticipant>();
        }
    
        public long PracticeSessionID { get; set; }
        public long CreatedByUserID { get; set; }
        public string DistrictCode { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string Title { get; set; }
        public Nullable<long> AnchorSessionID { get; set; }
        public Nullable<long> TrainingProtocolID { get; set; }
        public short PracticeSessionTypeID { get; set; }
        public short SchoolYear { get; set; }
        public Nullable<long> EvaluateeUserID { get; set; }
        public bool IsPrivate { get; set; }
        public short RandomDigits { get; set; }
    
        public virtual ICollection<SELearningWalkClassRoom> SELearningWalkClassRooms { get; set; }
        public virtual ICollection<SELearningWalkClassroomLabel> SELearningWalkClassroomLabels { get; set; }
        public virtual SEPracticeSessionType SEPracticeSessionType { get; set; }
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SETrainingProtocol SETrainingProtocol { get; set; }
        public virtual ICollection<SEPracticeSessionParticipant> SEPracticeSessionParticipants { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEUser SEUser1 { get; set; }
    }
}
