//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEPullQuote
    {
        public long PullQuoteID { get; set; }
        public long EvalSessionID { get; set; }
        public long FrameworkNodeID { get; set; }
        public string Quote { get; set; }
        public Nullable<bool> IsImportant { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual SEFrameworkNode SEFrameworkNode { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
    }
}
