//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEReportPrintOptionEvaluation
    {
        public long ReportPrintOptionEvaluationID { get; set; }
        public long ReportPrintOptionID { get; set; }
        public Nullable<long> EvaluationID { get; set; }
    
        public virtual SEReportPrintOption SEReportPrintOption { get; set; }
        public virtual SEEvaluation SEEvaluation { get; set; }
    }
}
