//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEReportPrintOptionEvalSession
    {
        public long ReportPrintOptionEvalSessionID { get; set; }
        public long ReportPrintOptionID { get; set; }
        public Nullable<long> EvalSessionID { get; set; }
    
        public virtual SEReportPrintOption SEReportPrintOption { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
    }
}
