//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEReportSnapshot
    {
        public long ReportSnapshotID { get; set; }
        public short ReportTypeID { get; set; }
        public Nullable<long> RepositoryItemID { get; set; }
        public short SchoolYear { get; set; }
        public bool IsPublic { get; set; }
        public string DistrictCode { get; set; }
    
        public virtual SEReportType SEReportType { get; set; }
        public virtual SESchoolYear SESchoolYear { get; set; }
    }
}
