//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEResource
    {
        public SEResource()
        {
            this.SERubricRows = new HashSet<SERubricRow>();
        }
    
        public long ResourceId { get; set; }
        public short ItemTypeID { get; set; }
        public Nullable<System.Guid> FileUUID { get; set; }
        public string WebUrl { get; set; }
        public string SchoolCode { get; set; }
        public string DistrictCode { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public string FileName { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public short ResourceType { get; set; }
    
        public virtual SEResourceItemType SEResourceItemType { get; set; }
        public virtual ICollection<SERubricRow> SERubricRows { get; set; }
    }
}
