//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEReportType
    {
        public SEReportType()
        {
            this.SEReportSnapshots = new HashSet<SEReportSnapshot>();
        }
    
        public short ReportTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEReportSnapshot> SEReportSnapshots { get; set; }
    }
}
