//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEReportPrintOption
    {
        public SEReportPrintOption()
        {
            this.SEReportPrintOptionEvalSessions = new HashSet<SEReportPrintOptionEvalSession>();
            this.SEReportPrintOptionEvaluatees = new HashSet<SEReportPrintOptionEvaluatee>();
            this.SEReportPrintOptionEvaluations = new HashSet<SEReportPrintOptionEvaluation>();
        }
    
        public long ReportPrintOptionID { get; set; }
        public short ReportPrintOptionTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentReportOptionID { get; set; }
    
        public virtual SEReportPrintOptionType SEReportPrintOptionType { get; set; }
        public virtual ICollection<SEReportPrintOptionEvalSession> SEReportPrintOptionEvalSessions { get; set; }
        public virtual ICollection<SEReportPrintOptionEvaluatee> SEReportPrintOptionEvaluatees { get; set; }
        public virtual ICollection<SEReportPrintOptionEvaluation> SEReportPrintOptionEvaluations { get; set; }
    }
}
