//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERubricPerformanceLevel
    {
        public SERubricPerformanceLevel()
        {
            this.SELearningWalkSessionScores = new HashSet<SELearningWalkSessionScore>();
            this.SEStudentGrowthGoals = new HashSet<SEStudentGrowthGoal>();
            this.SEStudentGrowthGoals1 = new HashSet<SEStudentGrowthGoal>();
            this.SEFrameworkPerformanceLevels = new HashSet<SEFrameworkPerformanceLevel>();
            this.SEEvaluations = new HashSet<SEEvaluation>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
            this.SESummativeFrameworkNodeScores = new HashSet<SESummativeFrameworkNodeScore>();
            this.SESummativeRubricRowScores = new HashSet<SESummativeRubricRowScore>();
            this.SEFrameworkNodeScores = new HashSet<SEFrameworkNodeScore>();
            this.SERubricRowScores = new HashSet<SERubricRowScore>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
        }
    
        public short PerformanceLevelID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short Sequence { get; set; }
    
        public virtual ICollection<SELearningWalkSessionScore> SELearningWalkSessionScores { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals1 { get; set; }
        public virtual ICollection<SEFrameworkPerformanceLevel> SEFrameworkPerformanceLevels { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
        public virtual ICollection<SESummativeFrameworkNodeScore> SESummativeFrameworkNodeScores { get; set; }
        public virtual ICollection<SESummativeRubricRowScore> SESummativeRubricRowScores { get; set; }
        public virtual ICollection<SEFrameworkNodeScore> SEFrameworkNodeScores { get; set; }
        public virtual ICollection<SERubricRowScore> SERubricRowScores { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
    }
}
