//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERubricRow
    {
        public SERubricRow()
        {
            this.SERubricRowFrameworkNodes = new HashSet<SERubricRowFrameworkNode>();
            this.SEStudentGrowthGoals = new HashSet<SEStudentGrowthGoal>();
            this.SEStudentGrowthGoals1 = new HashSet<SEStudentGrowthGoal>();
            this.SEResources = new HashSet<SEResource>();
            this.SEUserPrompts = new HashSet<SEUserPrompt>();
            this.SEStudentGrowthGoalBundles = new HashSet<SEStudentGrowthGoalBundle>();
            this.SERubricRowAnnotations = new HashSet<SERubricRowAnnotation>();
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
            this.SESummativeRubricRowScores = new HashSet<SESummativeRubricRowScore>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
            this.SESelfAssessments = new HashSet<SESelfAssessment>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
            this.SEAvailableEvidences = new HashSet<SEAvailableEvidence>();
        }
    
        public long RubricRowID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string PL4Descriptor { get; set; }
        public string PL3Descriptor { get; set; }
        public string PL2Descriptor { get; set; }
        public string PL1Descriptor { get; set; }
        public Nullable<System.Guid> XferID { get; set; }
        public Nullable<bool> IsStateAligned { get; set; }
        public string BelongsToDistrict { get; set; }
        public Nullable<bool> IsStudentGrowthAligned { get; set; }
        public string TitleToolTip { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.Guid> StickyID { get; set; }
    
        public virtual ICollection<SERubricRowFrameworkNode> SERubricRowFrameworkNodes { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals1 { get; set; }
        public virtual ICollection<SEResource> SEResources { get; set; }
        public virtual ICollection<SEUserPrompt> SEUserPrompts { get; set; }
        public virtual ICollection<SEStudentGrowthGoalBundle> SEStudentGrowthGoalBundles { get; set; }
        public virtual ICollection<SERubricRowAnnotation> SERubricRowAnnotations { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
        public virtual ICollection<SESummativeRubricRowScore> SESummativeRubricRowScores { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
        public virtual ICollection<SESelfAssessment> SESelfAssessments { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
        public virtual ICollection<SEAvailableEvidence> SEAvailableEvidences { get; set; }
    }
}
