//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERubricRowAnnotation
    {
        public SERubricRowAnnotation()
        {
            this.SEAvailableEvidences = new HashSet<SEAvailableEvidence>();
        }
    
        public long RubricRowAnnotationID { get; set; }
        public long RubricRowID { get; set; }
        public string Annotation { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ArtifactBundleID { get; set; }
        public Nullable<long> EvalSessionID { get; set; }
        public Nullable<long> StudentGrowthGoalBundleID { get; set; }
        public Nullable<int> AnnotationSourceType { get; set; }
        public long EvaluationID { get; set; }
        public short LinkedItemTypeID { get; set; }
    
        public virtual SERubricRow SERubricRow { get; set; }
        public virtual SEArtifactBundle SEArtifactBundle { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
        public virtual ICollection<SEAvailableEvidence> SEAvailableEvidences { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
