//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERubricRowFrameworkNode
    {
        public long FrameworkNodeID { get; set; }
        public long RubricRowID { get; set; }
        public short Sequence { get; set; }
    
        public virtual SEFrameworkNode SEFrameworkNode { get; set; }
        public virtual SERubricRow SERubricRow { get; set; }
    }
}
