//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESchoolConfiguration
    {
        public long SchoolConfigurationID { get; set; }
        public string DistrictCode { get; set; }
        public string SchoolCode { get; set; }
        public bool HasBeenSubmittedToDistrictTE { get; set; }
        public Nullable<System.DateTime> SubmissionToDistrictDateTE { get; set; }
        public bool IsPrincipalAssignmentDelegated { get; set; }
        public Nullable<short> SchoolYear { get; set; }
        public Nullable<long> PK_SESchoolConfiguration { get; set; }
        public bool IsStudentGrowthProcessSettingsDelegated { get; set; }
    }
}
