//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESchoolYear
    {
        public SESchoolYear()
        {
            this.SEEvalAssignmentRequests = new HashSet<SEEvalAssignmentRequest>();
            this.SEReportPrintOptionEvaluatees = new HashSet<SEReportPrintOptionEvaluatee>();
            this.SEReportSnapshots = new HashSet<SEReportSnapshot>();
            this.SEDistrictPRViewings = new HashSet<SEDistrictPRViewing>();
            this.SEUserPrompts = new HashSet<SEUserPrompt>();
            this.SEStudentGrowthProcessSettings = new HashSet<SEStudentGrowthProcessSetting>();
            this.SEUserPromptResponses = new HashSet<SEUserPromptResponse>();
            this.SEPracticeSessions = new HashSet<SEPracticeSession>();
            this.SEEvaluations = new HashSet<SEEvaluation>();
            this.SEStudentGrowthFormPromptFrameworkNodes = new HashSet<SEStudentGrowthFormPromptFrameworkNode>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
        }
    
        public short SchoolYear { get; set; }
        public string Description { get; set; }
        public string YearRange { get; set; }
    
        public virtual ICollection<SEEvalAssignmentRequest> SEEvalAssignmentRequests { get; set; }
        public virtual ICollection<SEReportPrintOptionEvaluatee> SEReportPrintOptionEvaluatees { get; set; }
        public virtual ICollection<SEReportSnapshot> SEReportSnapshots { get; set; }
        public virtual ICollection<SEDistrictPRViewing> SEDistrictPRViewings { get; set; }
        public virtual ICollection<SEUserPrompt> SEUserPrompts { get; set; }
        public virtual ICollection<SEStudentGrowthProcessSetting> SEStudentGrowthProcessSettings { get; set; }
        public virtual ICollection<SEUserPromptResponse> SEUserPromptResponses { get; set; }
        public virtual ICollection<SEPracticeSession> SEPracticeSessions { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations { get; set; }
        public virtual ICollection<SEStudentGrowthFormPromptFrameworkNode> SEStudentGrowthFormPromptFrameworkNodes { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
    }
}
