//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESelfAssessment
    {
        public SESelfAssessment()
        {
            this.SERubricRows = new HashSet<SERubricRow>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
        }
    
        public long SelfAssessmentID { get; set; }
        public long EvaluationID { get; set; }
        public long EvaluateeID { get; set; }
        public string ShortName { get; set; }
        public string Title { get; set; }
        public Nullable<short> PerformanceLevelID { get; set; }
        public bool IsSharedWithEvaluator { get; set; }
        public bool IsFocused { get; set; }
        public Nullable<long> FocusedFrameworkNodeID { get; set; }
        public Nullable<long> FocusedSGFrameworkNodeID { get; set; }
        public bool IncludeInFinalReport { get; set; }
        public System.DateTime CreationDateTime { get; set; }
    
        public virtual SEEvaluation SEEvaluation { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual ICollection<SERubricRow> SERubricRows { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
    }
}
