//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEStudentGrowthFormPromptFrameworkNode
    {
        public long StudentGrowthFormPromptFrameworkNodeID { get; set; }
        public string DistrictCode { get; set; }
        public short EvaluationTypeID { get; set; }
        public short SchoolYear { get; set; }
        public long FormPromptID { get; set; }
        public long FrameworkNodeID { get; set; }
    
        public virtual SEEvaluationType SEEvaluationType { get; set; }
        public virtual SEFrameworkNode SEFrameworkNode { get; set; }
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SEStudentGrowthFormPrompt SEStudentGrowthFormPrompt { get; set; }
    }
}
