//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEStudentGrowthGoalBundle
    {
        public SEStudentGrowthGoalBundle()
        {
            this.SEStudentGrowthGoals = new HashSet<SEStudentGrowthGoal>();
            this.SEStudentGrowthGoals1 = new HashSet<SEStudentGrowthGoal>();
            this.SERubricRows = new HashSet<SERubricRow>();
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
        }
    
        public long StudentGrowthGoalBundleID { get; set; }
        public long EvaluationID { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string Title { get; set; }
        public string Comments { get; set; }
        public string Course { get; set; }
        public string Grade { get; set; }
        public long WfStateID { get; set; }
        public long EvalWfStateID { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals { get; set; }
        public virtual SEWfState SEWfState { get; set; }
        public virtual ICollection<SEStudentGrowthGoal> SEStudentGrowthGoals1 { get; set; }
        public virtual ICollection<SERubricRow> SERubricRows { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
        public virtual SEWfState SEWfState1 { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
    }
}
