//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEStudentGrowthFormPrompt
    {
        public SEStudentGrowthFormPrompt()
        {
            this.SEStudentGrowthFormPromptFrameworkNodes = new HashSet<SEStudentGrowthFormPromptFrameworkNode>();
            this.SEStudentGrowthFormPromptResponses = new HashSet<SEStudentGrowthFormPromptResponse>();
            this.SEStudentGrowthProcessSettingsFormPrompts = new HashSet<SEStudentGrowthProcessSettingsFormPrompt>();
        }
    
        public long StudentGrowthFormPromptID { get; set; }
        public string Prompt { get; set; }
        public string DistrictCode { get; set; }
        public short EvaluationTypeID { get; set; }
        public short SchoolYear { get; set; }
        public short FormPromptTypeID { get; set; }
    
        public virtual SEStudentGrowthFormPromptType SEStudentGrowthFormPromptType { get; set; }
        public virtual ICollection<SEStudentGrowthFormPromptFrameworkNode> SEStudentGrowthFormPromptFrameworkNodes { get; set; }
        public virtual ICollection<SEStudentGrowthFormPromptResponse> SEStudentGrowthFormPromptResponses { get; set; }
        public virtual ICollection<SEStudentGrowthProcessSettingsFormPrompt> SEStudentGrowthProcessSettingsFormPrompts { get; set; }
    }
}
