//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEStudentGrowthFormPromptResponse
    {
        public long FormPromptResponseID { get; set; }
        public long FormPromptID { get; set; }
        public string Response { get; set; }
        public long UserID { get; set; }
        public Nullable<long> StudentGrowthGoalID { get; set; }
    
        public virtual SEStudentGrowthGoal SEStudentGrowthGoal { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEStudentGrowthFormPrompt SEStudentGrowthFormPrompt { get; set; }
    }
}
