//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEStudentGrowthProcessSettingsFormPrompt
    {
        public long ProcessSettingsFormPromptID { get; set; }
        public long ProcessSettingsID { get; set; }
        public long FormPromptID { get; set; }
        public bool Required { get; set; }
        public short Sequence { get; set; }
    
        public virtual SEStudentGrowthProcessSetting SEStudentGrowthProcessSetting { get; set; }
        public virtual SEStudentGrowthFormPrompt SEStudentGrowthFormPrompt { get; set; }
    }
}
