//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETrainingProtocol
    {
        public SETrainingProtocol()
        {
            this.SEDistrictTrainingProtocolAnchors = new HashSet<SEDistrictTrainingProtocolAnchor>();
            this.SETrainingProtocolFrameworkNodeAlignments = new HashSet<SETrainingProtocolFrameworkNodeAlignment>();
            this.SETrainingProtocolPlaylists = new HashSet<SETrainingProtocolPlaylist>();
            this.SETrainingProtocolRatings = new HashSet<SETrainingProtocolRating>();
            this.SETrainingProtocolLabels = new HashSet<SETrainingProtocolLabel>();
            this.SEPracticeSessions = new HashSet<SEPracticeSession>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
        }
    
        public long TrainingProtocolID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string DocName { get; set; }
        public string Length { get; set; }
        public bool Published { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public bool Retired { get; set; }
        public Nullable<bool> IncludeInPublicSite { get; set; }
        public Nullable<bool> IncludeInVideoLibrary { get; set; }
        public string VideoPoster { get; set; }
        public string VideoSrc { get; set; }
        public string ImageName { get; set; }
        public Nullable<short> AvgRating { get; set; }
        public Nullable<short> NumRatings { get; set; }
    
        public virtual ICollection<SEDistrictTrainingProtocolAnchor> SEDistrictTrainingProtocolAnchors { get; set; }
        public virtual ICollection<SETrainingProtocolFrameworkNodeAlignment> SETrainingProtocolFrameworkNodeAlignments { get; set; }
        public virtual ICollection<SETrainingProtocolPlaylist> SETrainingProtocolPlaylists { get; set; }
        public virtual ICollection<SETrainingProtocolRating> SETrainingProtocolRatings { get; set; }
        public virtual ICollection<SETrainingProtocolLabel> SETrainingProtocolLabels { get; set; }
        public virtual ICollection<SEPracticeSession> SEPracticeSessions { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
    }
}
