//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETrainingProtocolLabel
    {
        public SETrainingProtocolLabel()
        {
            this.SETrainingProtocols = new HashSet<SETrainingProtocol>();
        }
    
        public short TrainingProtocolLabelID { get; set; }
        public short TrainingProtocolLabelGroupID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Sequence { get; set; }
    
        public virtual SETrainingProtocolLabelGroup SETrainingProtocolLabelGroup { get; set; }
        public virtual ICollection<SETrainingProtocol> SETrainingProtocols { get; set; }
    }
}
