//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETrainingProtocolRating
    {
        public long TrainingProtocolRatingID { get; set; }
        public long TrainingProtocolID { get; set; }
        public long UserID { get; set; }
        public short Rating { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool IsAnnonymous { get; set; }
        public short Status { get; set; }
    
        public virtual SETrainingProtocol SETrainingProtocol { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
