//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETrainingProtocolHighLeveragePractice
    {
        public SETrainingProtocolHighLeveragePractice()
        {
            this.SETrainingProtocols = new HashSet<SETrainingProtocol>();
        }
    
        public long TrainingProtocolHighLeveragePracticeID { get; set; }
        public string ShortName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SETrainingProtocol> SETrainingProtocols { get; set; }
    }
}
