//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserPromptType
    {
        public SEUserPromptType()
        {
            this.SEUserPrompts = new HashSet<SEUserPrompt>();
            this.SEUserPromptConferenceDefaults = new HashSet<SEUserPromptConferenceDefault>();
        }
    
        public short UserPromptTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEUserPrompt> SEUserPrompts { get; set; }
        public virtual ICollection<SEUserPromptConferenceDefault> SEUserPromptConferenceDefaults { get; set; }
    }
}
