//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserLocationRole
    {
        public long UserLocationRoleID { get; set; }
        public Nullable<long> SEUserId { get; set; }
        public string UserName { get; set; }
        public string RoleName { get; set; }
        public System.Guid RoleId { get; set; }
        public string DistrictCode { get; set; }
        public string SchoolCode { get; set; }
        public Nullable<bool> LastActiveRole { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
