//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserPromptConferenceDefault
    {
        public long SEUserPromptConferenceDefaultID { get; set; }
        public long UserPromptID { get; set; }
        public short UserPromptTypeID { get; set; }
        public long EvaluateeID { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<long> PK_SEUserPromptConferenceDefault { get; set; }
    
        public virtual SEUser SEUser { get; set; }
        public virtual SEUserPrompt SEUserPrompt { get; set; }
        public virtual SEUserPromptType SEUserPromptType { get; set; }
    }
}
