//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserPromptRubricRowAlignment
    {
        public long SEUserPromptRubricRowAlignmentID { get; set; }
        public long UserPromptID { get; set; }
        public long RubricRowID { get; set; }
        public long CreatedByUserID { get; set; }
        public Nullable<long> PK_SEUserPromptRubricRowAlignment { get; set; }
    
        public virtual SERubricRow SERubricRow { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEUserPrompt SEUserPrompt { get; set; }
    }
}
