//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserPrompt
    {
        public SEUserPrompt()
        {
            this.SEUserPromptConferenceDefaults = new HashSet<SEUserPromptConferenceDefault>();
            this.SEUserPromptResponses = new HashSet<SEUserPromptResponse>();
            this.SERubricRows = new HashSet<SERubricRow>();
        }
    
        public long UserPromptID { get; set; }
        public short PromptTypeID { get; set; }
        public string Title { get; set; }
        public string Prompt { get; set; }
        public string DistrictCode { get; set; }
        public string SchoolCode { get; set; }
        public long CreatedByUserID { get; set; }
        public bool Published { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public bool Retired { get; set; }
        public short EvaluationTypeID { get; set; }
        public bool Private { get; set; }
        public Nullable<long> EvaluateeID { get; set; }
        public Nullable<long> EvalSessionID { get; set; }
        public bool CreatedAsAdmin { get; set; }
        public Nullable<short> Sequence { get; set; }
        public short SchoolYear { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<long> WfStateID { get; set; }
    
        public virtual SEEvaluationType SEEvaluationType { get; set; }
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SEUserPromptType SEUserPromptType { get; set; }
        public virtual ICollection<SEUserPromptConferenceDefault> SEUserPromptConferenceDefaults { get; set; }
        public virtual ICollection<SEUserPromptResponse> SEUserPromptResponses { get; set; }
        public virtual SEWfState SEWfState { get; set; }
        public virtual ICollection<SERubricRow> SERubricRows { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
        public virtual SEUser SEUser { get; set; }
        public virtual SEUser SEUser1 { get; set; }
    }
}
