//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserPromptResponse
    {
        public SEUserPromptResponse()
        {
            this.SEUserPromptResponseEntries = new HashSet<SEUserPromptResponseEntry>();
        }
    
        public long UserPromptResponseID { get; set; }
        public long UserPromptID { get; set; }
        public Nullable<long> EvaluateeID { get; set; }
        public Nullable<long> EvalSessionID { get; set; }
        public Nullable<short> SchoolYear { get; set; }
        public Nullable<long> ArtifactID { get; set; }
        public string DistrictCode { get; set; }
    
        public virtual SESchoolYear SESchoolYear { get; set; }
        public virtual SEUserPrompt SEUserPrompt { get; set; }
        public virtual ICollection<SEUserPromptResponseEntry> SEUserPromptResponseEntries { get; set; }
        public virtual SEEvalSession SEEvalSession { get; set; }
        public virtual SEUser SEUser { get; set; }
    }
}
