//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEUserDistrictSchool
    {
        public long UserDistrictSchoolID { get; set; }
        public long SEUserID { get; set; }
        public string SchoolCode { get; set; }
        public string DistrictCode { get; set; }
        public string SchoolName { get; set; }
        public string DistrictName { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual SEUser SEUser { get; set; }
    }
}
