//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEWfState
    {
        public SEWfState()
        {
            this.SEUserPrompts = new HashSet<SEUserPrompt>();
            this.SEWfTransitions = new HashSet<SEWfTransition>();
            this.SEWfTransitions1 = new HashSet<SEWfTransition>();
            this.SEStudentGrowthGoalBundles = new HashSet<SEStudentGrowthGoalBundle>();
            this.SEEvalSessions = new HashSet<SEEvalSession>();
            this.SEEvaluations = new HashSet<SEEvaluation>();
            this.SEArtifactBundles = new HashSet<SEArtifactBundle>();
            this.SERubricRowEvaluations = new HashSet<SERubricRowEvaluation>();
            this.SEStudentGrowthGoalBundles1 = new HashSet<SEStudentGrowthGoalBundle>();
        }
    
        public long WfStateID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SEUserPrompt> SEUserPrompts { get; set; }
        public virtual ICollection<SEWfTransition> SEWfTransitions { get; set; }
        public virtual ICollection<SEWfTransition> SEWfTransitions1 { get; set; }
        public virtual ICollection<SEStudentGrowthGoalBundle> SEStudentGrowthGoalBundles { get; set; }
        public virtual ICollection<SEEvalSession> SEEvalSessions { get; set; }
        public virtual ICollection<SEEvaluation> SEEvaluations { get; set; }
        public virtual ICollection<SEArtifactBundle> SEArtifactBundles { get; set; }
        public virtual ICollection<SERubricRowEvaluation> SERubricRowEvaluations { get; set; }
        public virtual ICollection<SEStudentGrowthGoalBundle> SEStudentGrowthGoalBundles1 { get; set; }
    }
}
