//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateLog
    {
        public long UpdateLogID { get; set; }
        public long BugNumber { get; set; }
        public string UpdateName { get; set; }
        public string Comment { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
