//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StateEvalData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserOrientation
    {
        public long FrameworkContextID { get; set; }
        public short SchoolYear { get; set; }
        public long UserDistrictSchoolID { get; set; }
        public string DistrictCode { get; set; }
        public string SchoolCode { get; set; }
        public short EvaluationTypeID { get; set; }
        public System.Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public long SEUserID { get; set; }
        public string DistrictName { get; set; }
        public string SchoolName { get; set; }
    }
}
