IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ProtoFrameworksToLoad]') AND type in (N'U'))
BEGIN
DROP TABLE dbo.ProtoFrameworksToLoad
END
GO

CREATE TABLE dbo.ProtoFrameworksToLoad (dest VARCHAR(7), src VARCHAR(7), placeName VARCHAR(50)
, schoolYear INT, Leader VARCHAR (10))

go

insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '14005', 'Aberdeen School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21226', 'Adna School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '22017', 'Almira School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '29103', 'Anacortes School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31016', 'Arlington School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '02420', 'Asotin-Anatone School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17408', 'Auburn School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '18303', 'Bainbridge Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '06119', 'Battle Ground School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17405', 'Bellevue School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37501', 'Bellingham School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27403', 'Bethel School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '20203', 'Bickleton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37503', 'Blaine School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21234', 'Boistfort School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '18100', 'Bremerton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24111', 'Brewster School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '09075', 'Bridgeport School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '16046', 'Brinnon School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '29100', 'Burlington-Edison School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '06117', 'Camas School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '05401', 'Cape Flattery School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '27019', 'Carbonado School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '04228', 'Cascade School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '04222', 'Cashmere School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '08401', 'Castle Rock School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '20215', 'Centerville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '18401', 'Central Kitsap School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '32356', 'Central Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21401', 'Centralia School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21302', 'Chehalis School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32360', 'Cheney School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '33036', 'Chewelah School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '16049', 'Chimacum School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '02250', 'Clarkston School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '19404', 'Cle Elum-Roslyn School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27400', 'Clover Park School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38300', 'Colfax School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36250', 'College Place School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38306', 'Colton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '33206', 'Columbia (Stevens) School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36400', 'Columbia (Walla Walla) School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '33115', 'Colville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '29011', 'Concrete School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '29317', 'Conway School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '14099', 'Cosmopolis School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '13151', 'Coulee-Hartline School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '15204', 'Coupeville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '05313', 'Crescent School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '22073', 'Creston School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '10050', 'Curlew School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '26059', 'Cusick School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '19007', 'Damman School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31330', 'Darrington School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '22207', 'Davenport School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '07002', 'Dayton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '32414', 'Deer Park School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27343', 'Dieringer School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36101', 'Dixie School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '32361', 'East Valley School District (Spokane)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39090', 'East Valley School District (Yakima)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '09206', 'Eastmont School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '19028', 'Easton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '27404', 'Eatonville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31015', 'Edmonds School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '19401', 'Ellensburg School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '14068', 'Elma School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38308', 'Endicott School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '04127', 'Entiat School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17216', 'Enumclaw School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '13165', 'Ephrata School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '32801', 'ESD 101 As District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '18801', 'ESD 114 As District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '11801', 'ESD 123 As District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '29801', 'ESD 189 AS District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '21036', 'Evaline School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31002', 'Everett School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '06114', 'Evergreen School District (Clark)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '33205', 'Evergreen School District (Stevens)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17210', 'Federal Way School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37502', 'Ferndale School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '27417', 'Fife School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '03053', 'Finley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27402', 'Franklin Pierce School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32358', 'Freeman School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38302', 'Garfield School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '20401', 'Glenwood School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '20404', 'Goldendale School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '13301', 'Grand Coulee Dam School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39200', 'Grandview School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39204', 'Granger School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31332', 'Granite Falls School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '23054', 'Grapeview School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32312', 'Great Northern School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '06103', 'Green Mountain School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '34324', 'Griffin School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '22204', 'Harrington School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39203', 'Highland School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17401', 'Highline School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '06098', 'Hockinson School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '23404', 'Hood Canal School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '14028', 'Hoquiam School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '10070', 'Inchelium School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31063', 'Index School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17411', 'Issaquah School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '11056', 'Kahlotus School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '08402', 'Kalama School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '10003', 'Keller School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '08458', 'Kelso School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '03017', 'Kennewick School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17415', 'Kent School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '33212', 'Kettle Falls School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '03052', 'Kiona-Benton City School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '19403', 'Kittitas School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '20402', 'Klickitat School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '06101', 'La Center School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '29311', 'La Conner School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38126', 'LaCrosse School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '04129', 'Lake Chelan School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '14097', 'Lake Quinault School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31004', 'Lake Stevens School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17414', 'Lake Washington School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31306', 'Lakewood School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38264', 'Lamont School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '32362', 'Liberty School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '01158', 'Lind School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '08122', 'Longview School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '33183', 'Loon Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '28144', 'Lopez School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '20406', 'Lyle School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37504', 'Lynden School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39120', 'Mabton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '09207', 'Mansfield School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '04019', 'Manson School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '23311', 'Mary M Knight School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '33207', 'Mary Walker School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31025', 'Marysville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '14065', 'McCleary School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32354', 'Mead School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '32326', 'Medical Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17400', 'Mercer Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37505', 'Meridian School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '24350', 'Methow Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '30031', 'Mill A School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31103', 'Monroe School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '14066', 'Montesano School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '21214', 'Morton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '13161', 'Moses Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '21206', 'Mossyrock School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39209', 'Mount Adams School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '37507', 'Mount Baker School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '30029', 'Mount Pleasant School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '29320', 'Mount Vernon School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31006', 'Mukilteo School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39003', 'Naches Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '21014', 'Napavine School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '25155', 'Naselle-Grays River Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24014', 'Nespelem School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '26056', 'Newport School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32325', 'Nine Mile Falls School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '37506', 'Nooksack Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '14064', 'North Beach School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '11051', 'North Franklin School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '18400', 'North Kitsap School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bDAN', '23403', 'North Mason School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '25200', 'North River School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '34003', 'North Thurston Public Schools')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '33211', 'Northport School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17417', 'Northshore School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '15201', 'Oak Harbor School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38324', 'Oakesdale School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '14400', 'Oakville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '25101', 'Ocean Beach School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '14172', 'Ocosta School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '22105', 'Odessa School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '24105', 'Okanogan School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '34111', 'Olympia School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24019', 'Omak School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21300', 'Onalaska School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '33030', 'Onion Creek School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '28137', 'Orcas Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '32123', 'Orchard Prairie School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '10065', 'Orient School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '09013', 'Orondo School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24410', 'Oroville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '27344', 'Orting School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '01147', 'Othello School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '09102', 'Palisades School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38301', 'Palouse School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '11001', 'Pasco School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24122', 'Pateros School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '03050', 'Paterson School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21301', 'Pe Ell School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27401', 'Peninsula School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '23402', 'Pioneer School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '12110', 'Pomeroy School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '05121', 'Port Angeles School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '16050', 'Port Townsend School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36402', 'Prescott School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '03116', 'Prosser School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '38267', 'Pullman School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bDAN', '27003', 'Puyallup School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bCEL', '16020', 'Queets-Clearwater School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '16048', 'Quilcene School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '05402', 'Quillayute Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '13144', 'Quincy School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '34307', 'Rainier School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '25116', 'Raymond School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '22009', 'Reardan-Edwall School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17403', 'Renton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '10309', 'Republic School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '03400', 'Richland School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '06122', 'Ridgefield School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '01160', 'Ritzville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '32416', 'Riverside School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17407', 'Riverview School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '34401', 'Rochester School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '20403', 'Roosevelt School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38320', 'Rosalia School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '13160', 'Royal School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '28149', 'San Juan Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '14104', 'Satsop School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17001', 'Seattle Public Schools')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '29101', 'Sedro-Woolley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39119', 'Selah School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '26070', 'Selkirk School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '05323', 'Sequim School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '28010', 'Shaw Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '23309', 'Shelton School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17412', 'Shoreline School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '30002', 'Skamania School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17404', 'Skykomish School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '31201', 'Snohomish School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '17410', 'Snoqualmie Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '13156', 'Soap Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '25118', 'South Bend School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '18402', 'South Kitsap School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '15206', 'South Whidbey School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '23042', 'Southside School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32081', 'Spokane School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '22008', 'Sprague School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38322', 'St. John School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31401', 'Stanwood-Camano School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '11054', 'Star School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '07035', 'Starbuck School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '04069', 'Stehekin School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27001', 'Steilacoom Hist. School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38304', 'Steptoe School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '30303', 'Stevenson-Carson School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '31311', 'Sultan School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '33202', 'Summit Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '27320', 'Sumner School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39201', 'Sunnyside School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '27010', 'Tacoma School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '14077', 'Taholah School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '17409', 'Tahoma School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '38265', 'Tekoa School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '34402', 'Tenino School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '19400', 'Thorp School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '21237', 'Toledo School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '24404', 'Tonasket School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39202', 'Toppenish School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '36300', 'Touchet School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '08130', 'Toutle Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '20400', 'Trout Lake School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '17406', 'Tukwila School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '34033', 'Tumwater School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39002', 'Union Gap School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '27083', 'University Place School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bMARPR','bMAR', '33070', 'Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '06037', 'Vancouver School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '17402', 'Vashon Island School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '35200', 'Wahkiakum School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '13073', 'Wahluke School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36401', 'Waitsburg School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '36140', 'Walla Walla Public Schools')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39207', 'Wapato School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '13146', 'Warden School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '06112', 'Washougal School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '01109', 'Washtucna School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '09209', 'Waterville School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '33049', 'Wellpinit School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '04246', 'Wenatchee School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '32363', 'West Valley School District (Spokane)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39208', 'West Valley School District (Yakima)')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '21303', 'White Pass School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '27416', 'White River School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '20405', 'White Salmon Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '22200', 'Wilbur School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '25160', 'Willapa Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '13167', 'Wilson Creek School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '21232', 'Winlock School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '14117', 'Wishkah Valley School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '20094', 'Wishram School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '08404', 'Woodland School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bDAN', '39007', 'Yakima School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bMAR', '34002', 'Yelm School District')
insert dbo.ProtoFrameworksToLoad(schoolYear, leader, src, dest, placename) values (2016, 'bprin','bCEL', '39205', 'Zillah School District')
