--central valley
update seRubricRow set pl1Descriptor = 'Not applicable. <b>  or </b>  Minimum requirement not met.  <i> (Comment required) </i>'
where RubricRowID in (48 ,60 ,54 ,65,50 ,61 ,55 ,66 ,51 ,62 ,56 ,67,52 ,63 ,57 ,68 ,53 ,64 ,58 ,69 ,59 ,70 ,71)

update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the importance for a school to have a shared mission, vision, beliefs, and goals.</li><li>Possesses well-defined ideals and beliefs about schools and schooling that align with the District Strategic Plan.</li><li>Understands the characteristics of a collaborative work environment.                                                                                                                           ') where rubricRowID=48                         
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands district policies and procedures regarding school safety.</li><li>Implements district policies and procedures regarding school safety.</li><li>Understands district policies and procedures regarding student discipline.</li><li>Implements district policies and procedures regarding student discipline.                                                                                                         ') where rubricRowID=50                       
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Knows the district-adopted SIP format and procedures.</li><li>Communicates to the entire school community the importance of developing a data-driven plan.</li><li>Leads and guides the development of a data drivenplan using                                                                                                                                                                                                  ') where rubricRowID=51                                         
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Articulates knowledge of curriculum, instruction, and assessments needed to initiate the implementation of the datadriven SIP.</li><li>Conveys a positive attitude about the staff&rsquo;s ability to implement the plan with fidelity.</li><li>Communicates with staff regarding the appropriate use of collaboration time.                                                                                                    ') where rubricRowID=52                 
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Identifies benchmark data points to be used in evaluating the effectiveness of the SIP.                                                                                                                                                                                                                                                                                                                                         ') where rubricRowID=53                                                                             
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Possesses knowledge of state learning goals.</li><li>Initiates formal and informal discussions that address curriculum, instruction, and assessment issues.</li><li>Possesses knowledge of best practice of instruction and assessment.</li><li>Encourages and supports meaningful professional learning opportunities.</li><li>Recognizes a variety of formative and summative assessments for the diagnosis of learner needs. ') where rubricRowID=54
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the importance of both formal and informal monitoring practices.</li><li>Communicates knowledge of instruction, assessment and evaluation.</li><li>Recognizes the components of a quality lesson.                                                                                                                                                                                                                   ') where rubricRowID=55                                                 
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Assesses the resource needs of teachers and staff.</li><li>Understands the importance of clear expectations, structures, and procedures for managing fiscal resources.</li><li>Understands the school funding, budget development, and budget management processes.</li><li>Understands the importance of non-fiscal resources (e.g., personnel, time, materials, etc.) in the effectiveness of a school.                       ') where rubricRowID=56               
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the importance of effectively recruiting, hiring, and mentoring new staff members.</li><li>Adheres to district policy for teacher and staff evaluation.</li><li>Understands the importance of clear expectations, structures, and procedures for managing human resources.                                                                                                                                          ') where rubricRowID=57                                 
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the importance of open, effective communication between and within school and district administration</li><li>Responds to parents, teachers, and patrons in a timely manner.</li><li>Communicates with stakeholder groups about school initiatives and activities.                                                                                                                                                  ') where rubricRowID=58                                         
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Acknowledges the importance of engaging stakeholder groups in meaningful ways.                                                                                                                                                                                                                                                                                                                                                  ') where rubricRowID=59                                                                             
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands relevant research on the achievement gap.</li><li>Communicates and models the ideals and beliefs that teachers and staff can impact student learning and achievement for all students.</li><li>Engages in frequent quality interactions with underperforming students.</li><li>Understands how to use data to identify achievement gaps.                                                                            ') where rubricRowID=60                       
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the need for high expectations for all students.</li><li>Establishes instructional goals based on mandated assessments.                                                                                                                                                                                                                                                                                             ') where rubricRowID=61                                                                   
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates knowledge of a core set of research-based instructional strategies.</li><li>Identifies instructional strategies that promote problem solving and critical thinking.</li><li>Understands the importance of using available technology.                                                                                                                                                                              ') where rubricRowID=62                                                 
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates an awareness of the value of feedback as a learning strategy.                                                                                                                                                                                                                                                                                                                                                      ') where rubricRowID=63                                                                             
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Understands the varying developmental needs of students.</li><li>Identifies resources to address individual student needs.                                                                                                                                                                                                                                                                                                      ') where rubricRowID=64                                                                   
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates how daily lessons are consistently aligned to the state&rsquo;s standards.</li><li>Standards are presented to students.                                                                                                                                                                                                                                                                                            ') where rubricRowID=65                                                                   
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates knowledge of state standards.</li><li>Demonstrates a basic understanding of the district&rsquo;s approved curriculum.                                                                                                                                                                                                                                                                                              ') where rubricRowID=66                                                                   
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Interacts with professionalism and positive intent with students.</li><li>Demonstrates sensitivity to the diversity of students in the classroom.</li><li>Develops routines and procedures that provide a safe and orderly classroom.                                                                                                                                                                                           ') where rubricRowID=67                                         
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates an awareness of a variety of assessment methods.</li><li>Communicates specified criteria to students.</li><li>Understands the importance of improved teaching practice and student learning based on assessment results.                                                                                                                                                                                           ') where rubricRowID=68                                                 
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Demonstrates an awareness of the needs of the intended audience.</li><li>Develops a plan for communicating with families regarding student performance.</li><li>Reads district/school-wide communications.</li><li>Adheres to confidentiality policies.                                                                                                                                                                         ') where rubricRowID=69                                       
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Professionally collaborates with colleagues.</li><li>Frequently communicates with colleagues regarding student performance.                                                                                                                                                                                                                                                                                                     ') where rubricRowID=70                                                                   
update seRubricRow set pl2Descriptor = rtrim('<ul><li>Sets professional goals directly related to professional growth.</li><li>Attends professional learning activities that are related directly to professional growth.                                                                                                                                                                                                                                                             ') where rubricRowID=71  

update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Leads the development of a shared mission, vision, beliefs, and goals for the school aligned with the School Improvement Plan (SIP) and the District Strategic Plan. </li><li> Communicates shared mission, vision, beliefs, and goals to the district and community stakeholders. </li><li> Creates an environment of collaboration and trust throughout the school.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                          48
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Reviews, analyzes, and implements school safety and discipline plans based on school data. </li><li> Establishes and enforces policies and routines that maximize opportunities for all students to learn.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                     50
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Leads the implementation of a data- driven plan. </li><li> Continues to monitor and adjust the plan using current data from multiple sources. </li><li> Provides support to teachers to implement the data-driven plan at the classroom and school level. </li><li> Prioritizes the appropriate use of resources to</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                            51
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Provides support to teachers to develop and examine formative and summative data. </li><li> Provides professional development around how to use data and how to analyze student work. </li><li> Prioritizes the appropriate use of resources to support the goals of the School Improvement Plan. </li><li> Facilitates the successful execution of the School Improvement Plan.</li></ul>') where RubricRowID =                                                                                                                                                                                                                               52
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Uses multiple forms of relevant data to evaluate the effectiveness of the plan to improve student learning. </li><li> Uses available data to adapt and revise the SIP as needed.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                               53
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Guides and/or instructs professional learning activities to address curriculum, instruction, and assessment issues that build on teachers&rsquo; strengths in reaching all students. </li><li> Initiates and leads discussions regarding quality of student work within and across teams. </li><li> Engages with staff in meaningful professional learning. </li><li> Sets expectations that teachers implement appropriate learning interventions to improve student learning. </li><li> Monitors teachers&rsquo; implementation of learning interventions and provides corrective support when necessary.</li></ul>') where RubricRowID =    54
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Uses a variety of formal and informal monitoring practices. </li><li> Implements the personnel evaluation system with fidelity and consistency. </li><li> Initiates opportunities for teachers to engage in professional dialog and activities to support instruction and assessment practices. </li><li> Provides opportunities for targeted professional learning as appropriate.</li></ul>') where RubricRowID =                                                                                                                                                                                                                            55
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Allocates material resources in ways which support student achievement. </li><li> Allocates professional learning resources in ways which support student achievement. </li><li> Allocates and protects time resources in ways which support student achievement. </li><li> Uses data to create, manage, and evaluate budget procedures. </li><li> Communicates the structure and rationale for decisions about resource allocation.</li></ul>') where RubricRowID =                                                                                                                                                                           56
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Uses hiring protocols that reflect student achievement goals. </li><li> Implements district personnel evaluation policies in a fair and equitable manner. </li><li> Implements and enforces policies and procedures. </li><li> Uses the recruitment and hiring processes strategically to further the school&rsquo;s vision and mission.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                       57
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Uses a variety of formats to communicate about student learning with stakeholders within and outside the school. </li><li> Uses effective communication skills and strategies to: </li><li> Enlist community support. </li><li> Resolve conflicts among individuals and groups. </li><li> Build common focus and collaboration to enhance student learning.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                    58
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Provides opportunities for stakeholder groups to become involved in the school. </li><li> Collaborates with administrative colleagues.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                                                                         59
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Implements school-wide practices that foster understanding and respect for cultural diversity, celebrates the contributions of diverse groups, and addresses closing the achievement gap. </li><li> Analyzes multiple data sources of sub-population groups of students to set targeted SIP goals and apply intervention programs to close achievement gaps. (Including effects of poverty, trauma, homelessness, etc.) </li><li> Actively participates in the development of district goals, strategic planning, and initiatives designed to improve student achievement and address achievement gaps.</li></ul>') where RubricRowID =        60
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Communicates high expectations for all students. </li><li> Establishes instructional goals based on multiple measures of student achievement data. </li><li> Promotes student involvement in the goal-setting process.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                         61
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Appropriately uses researchbased instructional strategies and resources necessary to meet the needs of all students. </li><li> Monitors and adjusts instructional strategies within lessons based on anecdotal evidence. </li><li> Provides opportunities for students to extend and refine knowledge. </li><li> Provides opportunities for students to use knowledge meaningfully through a variety of strategies. </li><li> Utilizes available instructional technology.</li></ul>') where RubricRowID =                                                                                                                                     62
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Provides learners with timely and consistent feedback based on on-going formative assessments.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 63
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Utilizes available resources needed to address individual student needs. </li><li> Differentiates instruction based on regular review of individual student work.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                                              64
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Assists students in understanding the relevance of the standards. </li><li> Provides students with an appropriately challenging and rigorous curriculum. </li><li> Communicates standards in learner friendly language.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                        65
update serubricrow set pl3Descriptor=rtrim('<ul><li>Utilizes district approved curriculum and state standards in both short term and long term lesson development. </li><li> Utilizes instructional time to promote understanding of content.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                                 66
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Assures routines and procedures are in place that help students assume responsibility for themselves. </li><li> Routinely encourages contributions of all students. </li><li> Supports students of various backgrounds and abilities.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                          67
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Utilizes a variety of assessments that are aligned with learning targets and state standards. </li><li> Uses formal and informal assessment data to inform lesson planning and instructional decisions.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                        68
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Communicates in a timely and consistent manner with students, parents, guardians for the benefit of students. </li><li> Supports district/school mission and goals.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                                            69
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Collaborates with colleagues about best practices for improved student learning. </li><li> Professionally and confidentially shares with appropriate colleague&rsquo;s information that explains or helps inform about students&rsquo; academic performance.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                   70
update serubricrow set pl3Descriptor=rtrim('. . . and <ul><li> Contributes to the establishment of professional working relationships. </li><li> Proactively seeks resources and professional development opportunities to improve professional practice.</li></ul>') where RubricRowID =                                                                                                                                                                                                                                                                                                                                                                                                                     71


update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Continually evaluates the shared mission, vision, beliefs, and goals for the school that are aligned with the SIP and the District Strategic Plan and makes adaptations as appropriate. </li><li> Ensures that mission, vision, and goals drive decisionmaking and school culture. </li><li> Facilitates and sustains an environment of collaboration and trust to positively impact student achievement.  </li></ul>'                                                                                                                                                                                                      )  where rubricRowID = 48
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Ensures an orderly environment to maximize student learning.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )  where rubricRowID = 50
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Leads the analysis of the evaluation of the data-driven plan at the classroom and school level. </li><li> Empowers staff to participate in the development and implementation of the SIP. </li><li> Ensures that the goals of the SIP are implemented with fidelity and monitored frequently.  </li></ul>'                                                                                                                                                                                                                                                                                                                  )  where rubricRowID = 51
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Advocates for sustainable and continuous school improvement. </li><li> Fosters school and community commitment to the principles of sustainability and continuous improvement.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                   )  where rubricRowID = 52
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Models a commitment to continuous improvement through a systematic analysis of data. </li><li> Builds a school community where stakeholders are encouraged to understand and have a voice in the development and assessment of the SIP. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                         )  where rubricRowID = 53
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Models knowledge of researchbased best practice and expects staff to have an understanding of curriculum alignment processes within and across curriculum areas and grade levels. </li><li> Ensures that staff have multiple and various learning experiences to promote best practice.  </li></ul>'                                                                                                                                                                                                                                                                                                                        )  where rubricRowID = 54
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Monitors the fidelity and consistency of the implementation of researchbased practice. </li><li> Assists staff in monitoring and analyzing their own practice. </li><li> Empowers staff to reflect on the instructional skills and knowledge needed to positively impact student achievement.  </li></ul>'                                                                                                                                                                                                                                                                                                                  )  where rubricRowID = 55
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Implements procedures that ensure the long-term viability of effective programs and practices. </li><li> Implements process for input on resource allocation and budgetary decisions. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                           )  where rubricRowID = 56
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Facilitates ongoing support for new staff members and those who are taking on new or additional responsibilities and leadership roles. </li><li> Optimizes the school&rsquo;s human capital and the intangible assets of staff members to maximize opportunities for student achievement. </li><li> Systematically reviews and adjusts expectations and procedures on an ongoing basis.  </li></ul>'                                                                                                                                                                                                                        )  where rubricRowID = 57
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Systematically monitors and takes steps to ensure improved communication with the school community at large. </li><li> Models effective communication and expects staff to also communicate on a regular basis.  </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                )  where rubricRowID = 58
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Optimizes stakeholder involvement to provide learning opportunities for staff and students. </li><li> Engages the school community in the implementation of district strategic plan.  </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                           )  where rubricRowID = 59
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Continuously works with staff to increase staff understanding of how to close the achievement gap. </li><li> Works to build the collective efficacy of staff through shared understandings about students. </li><li> Systematically monitors student achievement of underperforming populations of students. </li><li> Optimizes school programs and community resources to integrate community, family language, and culture into the school to support the students'' academic progress.  </li></ul>'                                                                                                                     )  where rubricRowID = 60
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Ensures that students can communicate expectations for learning. </li><li> Consistently monitors student growth. </li><li> Consistently adjusts student goals based on ongoing use of achievement data. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                         )  where rubricRowID = 61
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Intentionally selects and implements instructional strategy for the cognitive requirements of the learning objective or lesson. </li><li> Provides students with multiple exposures to tasks that build skills and knowledge. </li><li> Purposefully assists students to incorporate the knowledge and skill from other academic disciplines. </li><li> Ensures that students can articulate procedures and strategies for becoming life-long problem solvers and critical thinkers. </li><li> Consistently utilizes emerging research and new and innovative instructional materials and available technologies.</li></ul>')  where rubricRowID = 62
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Creates opportunities for learners to monitor and analyze their own progress. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )  where rubricRowID = 63
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Consistently demonstrates an understanding of students&rsquo; unique learning abilities and appropriately addresses needs for optimal student learning. </li><li> Explicitly demonstrates how new learning builds on the prior learning of individual students.</li></ul>'                                                                                                                                                                                                                                                                                                                                                  )  where rubricRowID = 64
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Consistently provides opportunities for students to communicate their understanding of the standards.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )  where rubricRowID = 65
update seRubricrow set pl4Descriptor= rtrim('<ul><li>Continually provides leadership in the development and/or implementation of district curriculum. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )  where rubricRowID = 66
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Monitors and adjusts routines and procedures based on classroom dynamics. </li><li> Establishes a classroom community that empowers students to collaborate and maintain a safe and supportive environment.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                      )  where rubricRowID = 67
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Models the use of assessment information to adjust instructional practice for others. </li><li> Empowers students to engage in self-assessment.  </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                )  where rubricRowID = 68
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Builds relationships with parents and community by providing opportunities for twoway communication. </li><li> Communicates with the other professional educators within the school to promote improving individual student performance.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                         )  where rubricRowID = 69
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Promotes the success of all students through a focus on teamwork, trust, and collective efficacy. </li><li> Provides leadership in facilitating collaborative and collegial processes.</li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                           )  where rubricRowID = 70
update seRubricrow set pl4Descriptor= rtrim('. . . and <ul><li> Provides leadership for the professional learning of colleagues in the use of researchbased instructional strategies. </li></ul>'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )  where rubricRowID = 71


--consortium
update seRubricRow set
	Title = Replace(convert (varchar(3000),Title), '<br />', '')
	,PL1Descriptor = Replace(convert (varchar(3000),pl1Descriptor), '<br />', '')
	,PL2Descriptor = Replace(convert (varchar(3000),pl2Descriptor), '<br />', '')
	,PL3Descriptor = Replace(convert (varchar(3000),pl3Descriptor), '<br />', '')
	,PL4Descriptor = Replace(convert (varchar(3000),pl4Descriptor), '<br />', '')
where rubricRowID in (72,73,74,75,76,77,78,79,80,81,82,83)

update serubricrow set title = rtrim('1b: Demonstrating   knowledge of students             ') where rubricRowID =72
update serubricrow set title = rtrim('1c: Setting instructional   outcomes                  ') where rubricRowID =73
update serubricrow set title = rtrim('1f: Designing student   assessments                   ') where rubricRowID =74
update serubricrow set title = rtrim('2a: Creating an   environment of   respect and rapport') where rubricRowID =75
update serubricrow set title = rtrim('2b: Establishing a culture   for learning             ') where rubricRowID =76
update serubricrow set title = rtrim('2c: Managing classroom   procedures                   ') where rubricRowID =77
update serubricrow set title = rtrim('3b: Using questioning and   discussion techniques     ') where rubricRowID =78
update serubricrow set title = rtrim('3c: Engaging students in   learning                   ') where rubricRowID =79
update serubricrow set title = rtrim('3d: Using assessment in   instruction                 ') where rubricRowID =80
update serubricrow set title = rtrim('4a: Reflecting on teaching                            ') where rubricRowID =81
update serubricrow set title = rtrim('4c: Communicating with   families                     ') where rubricRowID =82
update serubricrow set title = rtrim('4d: Participating in a   professional   community     ') where rubricRowID =83

--north thurston ti
update seRubricRow set Title = rtrim ('Domain 1: Planning and Preparation      ') where rubricRowID=436
update seRubricRow set Title = rtrim ('Domain 2: The Classroom Environment     ') where rubricRowID=437
update seRubricRow set Title = rtrim ('Domain 3: Instruction                   ') where rubricRowID=438
update seRubricRow set Title = rtrim ('Domain 4: Professional Responsibilities ') where rubricRowID=439

update seRubricRow set
Title = Replace(convert (varchar(3000),Title), '<br />', '')
,PL1Descriptor = Replace(convert (varchar(3000),pl1Descriptor), '<br />', '')
,PL2Descriptor = Replace(convert (varchar(3000),pl2Descriptor), '<br />', '')
,PL3Descriptor = Replace(convert (varchar(3000),pl3Descriptor), '<br />', '')
,PL4Descriptor = Replace(convert (varchar(3000),pl4Descriptor), '<br />', '')
where RubricRowID in 
	(
		select rr.RubricRowID from SERubricRow rr
		join SERubricRowFrameworkNode rrfn on rrfn.RubricRowID = rr.RubricRowID
		join SEFrameworkNode fn on fn.FrameworkNodeID = rrfn.FrameworkNodeID
		where fn.FrameworkID in (12, 13, 14, 15)
	)


update seRubricRow set Title = rtrim('1.1: Commits to High   Learning   Expectations                                                                                                                                            ') where rubricRowID = 249
update seRubricRow set Title = rtrim('1.2: Promotes Pride &amp;   Effort                                                                                                                                                        ') where rubricRowID = 250
update seRubricRow set Title = rtrim('1.3: Fosters Original &amp;   Creative Thinking                                                                                                                                           ') where rubricRowID = 251
update seRubricRow set Title = rtrim('1.4: Student Engagement                                                                                                                                                                   ') where rubricRowID = 252
update seRubricRow set Title = rtrim('2.1: Daily &amp; Unit Lesson   Planning                                                                                                                                                   ') where rubricRowID = 253
update seRubricRow set Title = rtrim('2.2: Lesson Structure                                                                                                                                                                     ') where rubricRowID = 254
update seRubricRow set Title = rtrim('2.3: Instructional   Grouping                                                                                                                                                             ') where rubricRowID = 255
update seRubricRow set Title = rtrim('2.4: Directions &amp;   Procedures                                                                                                                                                        ') where rubricRowID = 256
update seRubricRow set Title = rtrim('2.5: Transitions                                                                                                                                                                          ') where rubricRowID = 257
update seRubricRow set Title = rtrim('2.6: Learning   Conversations                                                                                                                                                             ') where rubricRowID = 258
update seRubricRow set Title = rtrim('2.7: Lesson Improvement                                                                                                                                                                   ') where rubricRowID = 259
update seRubricRow set Title = rtrim('3.1: Student Prior   Knowledge                                                                                                                                                            ') where rubricRowID = 260
update seRubricRow set Title = rtrim('3.2: Students&rsquo; Special   Needs                                                                                                                                                      ') where rubricRowID = 261
update seRubricRow set Title = rtrim('3.3: Instructional   Strategies                                                                                                                                                           ') where rubricRowID = 262
update seRubricRow set Title = rtrim('3.5: Response to Student   Interest                                                                                                                                                       ') where rubricRowID = 263
update seRubricRow set Title = rtrim('4.1: District &amp; State   Standards                                                                                                                                                     ') where rubricRowID = 264
update seRubricRow set Title = rtrim('4.2: Content Knowledge                                                                                                                                                                    ') where rubricRowID = 265
update seRubricRow set Title = rtrim('4.3: Content-Related   Pedagogy                                                                                                                                                           ') where rubricRowID = 266
update seRubricRow set Title = rtrim('4.4: Interdisciplinary   Integration                                                                                                                                                      ') where rubricRowID = 267
update seRubricRow set Title = rtrim('4.5: Presentation of   Subject Matter   Content                                                                                                                                           ') where rubricRowID = 268
update seRubricRow set Title = rtrim('5.1: Teacher Interactions   with Students                                                                                                                                                 ') where rubricRowID = 269
update seRubricRow set Title = rtrim('5.2: Student Interactions   with Students                                                                                                                                                 ') where rubricRowID = 270
update seRubricRow set Title = rtrim('5.3: Monitoring of   Student Behavior                                                                                                                                                     ') where rubricRowID = 271
update seRubricRow set Title = rtrim('5.4: Response to Student   Misbehavior                                                                                                                                                    ') where rubricRowID = 272
update seRubricRow set Title = rtrim('5.5: Accessing Support   Services                                                                                                                                                         ') where rubricRowID = 273
update seRubricRow set Title = rtrim('5.6: Physical   Environment                                                                                                                                                               ') where rubricRowID = 274
update seRubricRow set Title = rtrim('5.7: Equipment                                                                                                                                                                            ') where rubricRowID = 275
update seRubricRow set Title = rtrim('6.1: Assessment Tools                                                                                                                                                                     ') where rubricRowID = 276
update seRubricRow set Title = rtrim('6.2: Data-Driven   Instructional   Planning                                                                                                                                               ') where rubricRowID = 277
update seRubricRow set Title = rtrim('6.3: Student Use of Data                                                                                                                                                                  ') where rubricRowID = 278
update seRubricRow set Title = rtrim('6.4: Assessment Criteria                                                                                                                                                                  ') where rubricRowID = 279
update seRubricRow set Title = rtrim('6.5: Assessment   Feedback                                                                                                                                                                ') where rubricRowID = 280
update seRubricRow set Title = rtrim('6.6: Data Analysis                                                                                                                                                                        ') where rubricRowID = 281
update seRubricRow set Title = rtrim('7.1: Communicating   Program   Information                                                                                                                                                ') where rubricRowID = 282
update seRubricRow set Title = rtrim('7.2: Communicating   Student Progress                                                                                                                                                     ') where rubricRowID = 283
update seRubricRow set Title = rtrim('7.3: Maintaining   Accurate Records                                                                                                                                                       ') where rubricRowID = 284
update seRubricRow set Title = rtrim('8.1: Performance   Feedback                                                                                                                                                               ') where rubricRowID = 285
update seRubricRow set Title = rtrim('8.2: Collaboration                                                                                                                                                                        ') where rubricRowID = 286
update seRubricRow set Title = rtrim('8.3: Professional   Responsibilities                                                                                                                                                      ') where rubricRowID = 287
update seRubricRow set Title = rtrim('8.4: Substitute Lesson   Planning                                                                                                                                                         ') where rubricRowID = 288
update seRubricRow set Title = rtrim('1.1: Continuous Improvement                                                                                                                                                               ') where rubricRowID = 289
update seRubricRow set Title = rtrim('1.2: Trusting and collaborative environment                                                                                                                                               ') where rubricRowID = 290
update seRubricRow set Title = rtrim('1.3: Mission and vision focused on learning and teaching                                                                                                                                  ') where rubricRowID = 291
update seRubricRow set Title = rtrim('1.4: Promoting data driven decision making                                                                                                                                                ') where rubricRowID = 292
update seRubricRow set Title = rtrim('2.1: Building and classroom discipline                                                                                                                                                    ') where rubricRowID = 293
update seRubricRow set Title = rtrim('2.2: Maintains a safe physical plant                                                                                                                                                      ') where rubricRowID = 294
update seRubricRow set Title = rtrim('2.3: Crisis Action Plan                                                                                                                                                                   ') where rubricRowID = 295
update seRubricRow set Title = rtrim('2.4: Prevention and training                                                                                                                                                              ') where rubricRowID = 296
update seRubricRow set Title = rtrim('3.1: Collaboratively develops an action plan based on data                                                                                                                                ') where rubricRowID = 297
update seRubricRow set Title = rtrim('3.2: Monitors implementation and effectiveness of the CIPP plan                                                                                                                           ') where rubricRowID = 298
update seRubricRow set Title = rtrim('3.3: Ensures alignment of the CIPP plan                                                                                                                                                   ') where rubricRowID = 299
update seRubricRow set Title = rtrim('3.4: Supports implementation of CIPP plan                                                                                                                                                 ') where rubricRowID = 300
update seRubricRow set Title = rtrim('4.1: Familiar with state and district standards                                                                                                                                           ') where rubricRowID = 301
update seRubricRow set Title = rtrim('4.2: Assists staff in the writing and use of formative and summative assessments                                                                                                          ') where rubricRowID = 303
update seRubricRow set Title = rtrim('4.3: Is familiar with and promotes district adopted instructional practices                                                                                                               ') where rubricRowID = 304
update seRubricRow set Title = rtrim('4.4: Supports staff collaboration that focuses on effective instruction, use of data, and common planning                                                                                 ') where rubricRowID = 305
update seRubricRow set Title = rtrim('4.5: Supports staff through professional development focused on state and district learning goals                                                                                         ') where rubricRowID = 306
update seRubricRow set Title = rtrim('5.1: Promotes and monitors use of adopted curriculum                                                                                                                                      ') where rubricRowID = 307
update seRubricRow set Title = rtrim('5.2: Uses a variety of measures and methods for observations                                                                                                                              ') where rubricRowID = 308
update seRubricRow set Title = rtrim('5.3: Uses a variety of data to monitor and improve instructional practices                                                                                                                ') where rubricRowID = 309
update seRubricRow set Title = rtrim('5.4: Uses the District evaluation process to provide staff with assistance and feedback to improve instruction                                                                            ') where rubricRowID = 310
update seRubricRow set Title = rtrim('6.1: Effectively manages Human Resources                                                                                                                                                  ') where rubricRowID = 311
update seRubricRow set Title = rtrim('6.1: Effectively manages Human Resources                                                                                                                                                  ') where rubricRowID = 312
update seRubricRow set Title = rtrim('6.2: Effectively manages school resources and budget                                                                                                                                      ') where rubricRowID = 313
update seRubricRow set Title = rtrim('6.3: Legal and Ethical Practice                                                                                                                                                           ') where rubricRowID = 314
update seRubricRow set Title = rtrim('7.1: Frequent and effective communication with parents and community.                                                                                                                     ') where rubricRowID = 315
update seRubricRow set Title = rtrim('7.2: Builds positive and collaborative collegial relationships.                                                                                                                           ') where rubricRowID = 316
update seRubricRow set Title = rtrim('7.3: Promotes positive and collaborative staff relationships.                                                                                                                             ') where rubricRowID = 317
update seRubricRow set Title = rtrim('7.4: Understands community dynamics and considers stakeholder input when making decisions.                                                                                                ') where rubricRowID = 318
update seRubricRow set Title = rtrim('7.5: Promotes parent and community involvement.                                                                                                                                           ') where rubricRowID = 319
update seRubricRow set Title = rtrim('8.1: Uses data to align resources and programs in closing the achievement gap                                                                                                             ') where rubricRowID = 320
update seRubricRow set Title = rtrim('8.2: Understands factors that contribute to the achievement gap                                                                                                                           ') where rubricRowID = 321
update seRubricRow set Title = rtrim('8.3: Student Growth Data                                                                                                                                                                  ') where rubricRowID = 322
update seRubricRow set Title = rtrim('1.1: The teacher asks questions of all students with the same frequency and depth.                                                                                                        ') where rubricRowID = 323
update seRubricRow set Title = rtrim('1.2: The teacher probes incorrect answers of all students in the same manner.                                                                                                             ') where rubricRowID = 324
update seRubricRow set Title = rtrim('2.1: The teacher facilitates the acquisition of new knowledge.                                                                                                                            ') where rubricRowID = 325
update seRubricRow set Title = rtrim('2.2: The teacher uses various methods to engage students.                                                                                                                                 ') where rubricRowID = 326
update seRubricRow set Title = rtrim('2.3: The teacher identifies appropriate academic vocabulary aligned to the learning target and uses various strategies for student <br />  acquisition.                                   ') where rubricRowID = 327
update seRubricRow set Title = rtrim('3.1: The teacher knows individual student learning needs to design instruction.                                                                                                           ') where rubricRowID = 328
update seRubricRow set Title = rtrim('3.2: The teacher provides interventions to meet individual student learning needs.                                                                                                        ') where rubricRowID = 329
update seRubricRow set Title = rtrim('3.3: The teacher plans and prepares for use of materials and technology.                                                                                                                  ') where rubricRowID = 330
update seRubricRow set Title = rtrim('4.1: The teacher has a comprehensive understanding of the subject(s) taught.                                                                                                              ') where rubricRowID = 331
update seRubricRow set Title = rtrim('4.2: The teacher skillfully uses the adopted curriculum.                                                                                                                                  ') where rubricRowID = 332
update seRubricRow set Title = rtrim('4.3: The teacher has a comprehensive understanding of the standards.                                                                                                                      ') where rubricRowID = 333
update seRubricRow set Title = rtrim('4.4: The teacher develops, aligns, and communicates clear learning targets/goals.                                                                                                         ') where rubricRowID = 334
update seRubricRow set Title = rtrim('5.1: The teacher organizes a safe, physical layout of the classroom to facilitate movement and focus on learning.                                                                         ') where rubricRowID = 335
update seRubricRow set Title = rtrim('5.2: The teacher reviews expectations regarding rules and procedures to ensure effective execution.                                                                                       ') where rubricRowID = 336
update seRubricRow set Title = rtrim('5.3: The teacher builds positive relationships with students.                                                                                                                             ') where rubricRowID = 337
update seRubricRow set Title = rtrim('6.1: The teacher uses multiple data elements to guide students in self-reflection and goal setting.                                                                                       ') where rubricRowID = 338
update seRubricRow set Title = rtrim('6.2: The teacher uses multiple data elements to modify instruction.                                                                                                                       ') where rubricRowID = 339
update seRubricRow set Title = rtrim('6.3: The teacher uses multiple data elements to design and modify appropriate student assessments.                                                                                        ') where rubricRowID = 340
update seRubricRow set Title = rtrim('6.4: The teacher can show that the students in his/her classroom have made growth and/or met course or grade-level standards using <br />  multiple measures.                             ') where rubricRowID = 341
update seRubricRow set Title = rtrim('7.1: The teacher communicates and collaborates with parents/guardians/school/community in a timely and professional manner <br />  regarding courses, programs, school events, and grade l') where rubricRowID = 342
update seRubricRow set Title = rtrim('7.2: The teacher communicates individual student progress to parents/guardians in a timely and professional manner and collaborates <br />  with parents in support of student learning.  ') where rubricRowID = 343
update seRubricRow set Title = rtrim('8.1: The teacher collaborates with colleagues about student learning and instructional practices.                                                                                         ') where rubricRowID = 344
update seRubricRow set Title = rtrim('8.2: The teacher displays dependability through active participation.                                                                                                                     ') where rubricRowID = 345
update seRubricRow set Title = rtrim('8.3: The teacher pursues professional development.                                                                                                                                        ') where rubricRowID = 346
update seRubricRow set Title = rtrim('8.4: The teacher meets growth targets as identified in annual professional goals.                                                                                                         ') where rubricRowID = 347
update seRubricRow set Title = rtrim('1.1: Culture&nbsp;&nbsp;&nbsp;&nbsp;                                                                                                                                                      ') where rubricRowID = 348
update seRubricRow set Title = rtrim('1.2: Relationships                                                                                                                                                                        ') where rubricRowID = 349
update seRubricRow set Title = rtrim('1.3: Communication                                                                                                                                                                        ') where rubricRowID = 350
update seRubricRow set Title = rtrim('1.4: Ideals/Beliefs                                                                                                                                                                       ') where rubricRowID = 351
update seRubricRow set Title = rtrim('1.5: Monitoring &amp; Evaluating                                                                                                                                                          ') where rubricRowID = 352
update seRubricRow set Title = rtrim('1.6: Situational Awareness                                                                                                                                                                ') where rubricRowID = 353
update seRubricRow set Title = rtrim('1.7: Visibility                                                                                                                                                                           ') where rubricRowID = 354
update seRubricRow set Title = rtrim('2.1: Safety Planning                                                                                                                                                                      ') where rubricRowID = 355
update seRubricRow set Title = rtrim('2.2: Response to Safety Problems                                                                                                                                                          ') where rubricRowID = 356
update seRubricRow set Title = rtrim('2.3: Physical &amp; Emotional Safety: Student Discipline                                                                                                                                  ') where rubricRowID = 357
update seRubricRow set Title = rtrim('2.4: Order                                                                                                                                                                                ') where rubricRowID = 358
update seRubricRow set Title = rtrim('3.1: Change Agent                                                                                                                                                                         ') where rubricRowID = 359
update seRubricRow set Title = rtrim('3.2: Input                                                                                                                                                                                ') where rubricRowID = 360
update seRubricRow set Title = rtrim('3.3: Focus                                                                                                                                                                                ') where rubricRowID = 361
update seRubricRow set Title = rtrim('3.4: Culturally Responsive Practices                                                                                                                                                      ') where rubricRowID = 362
update seRubricRow set Title = rtrim('3.5: Differentiation for High Performing &amp; Highly Capable Learner*                                                                                                                    ') where rubricRowID = 363
update seRubricRow set Title = rtrim('4.1: Knowledge of Curriculum, Instruction, and Assessment                                                                                                                                 ') where rubricRowID = 364
update seRubricRow set Title = rtrim('4.2: Involvement in Curriculum, Instruction &amp; Assessment                                                                                                                              ') where rubricRowID = 365
update seRubricRow set Title = rtrim('4.3: Guaranteed &amp; Viable Curriculum                                                                                                                                                   ') where rubricRowID = 366
update seRubricRow set Title = rtrim('4.4: Professional Learning Communities                                                                                                                                                    ') where rubricRowID = 367
update seRubricRow set Title = rtrim('4.5: Discipline                                                                                                                                                                           ') where rubricRowID = 368
update seRubricRow set Title = rtrim('5.1: Intellectual Stimulation                                                                                                                                                             ') where rubricRowID = 369
update seRubricRow set Title = rtrim('5.2: Effective Instruction in Every Classroom                                                                                                                                             ') where rubricRowID = 370
update seRubricRow set Title = rtrim('5.3: Affirmation                                                                                                                                                                          ') where rubricRowID = 371
update seRubricRow set Title = rtrim('5.4: Contingent Rewards                                                                                                                                                                   ') where rubricRowID = 372
update seRubricRow set Title = rtrim('5.5: Teacher Evaluation                                                                                                                                                                   ') where rubricRowID = 373
update seRubricRow set Title = rtrim('5.6: Focus on Results                                                                                                                                                                     ') where rubricRowID = 374
update seRubricRow set Title = rtrim('6.1: Resources                                                                                                                                                                            ') where rubricRowID = 375
update seRubricRow set Title = rtrim('6.2: Master Schedule                                                                                                                                                                      ') where rubricRowID = 410
update seRubricRow set Title = rtrim('6.3: Management &amp; Budget                                                                                                                                                              ') where rubricRowID = 411
update seRubricRow set Title = rtrim('6.4: Policy and Procedures                                                                                                                                                                ') where rubricRowID = 412
update seRubricRow set Title = rtrim('6.5: Development &amp; Expanding Leadership                                                                                                                                               ') where rubricRowID = 413
update seRubricRow set Title = rtrim('6.6: Flexibility                                                                                                                                                                          ') where rubricRowID = 414
update seRubricRow set Title = rtrim('7.1: Advocacy &amp; Communication with the Public                                                                                                                                         ') where rubricRowID = 415
update seRubricRow set Title = rtrim('7.2: Respect                                                                                                                                                                              ') where rubricRowID = 416
update seRubricRow set Title = rtrim('7.3: School Events                                                                                                                                                                        ') where rubricRowID = 417
update seRubricRow set Title = rtrim('7.4: Parent Groups                                                                                                                                                                        ') where rubricRowID = 418
update seRubricRow set Title = rtrim('3.6: District Improvement Efforts                                                                                                                                                         ') where rubricRowID = 419
update seRubricRow set Title = rtrim('3.7: Disaggrgating Data                                                                                                                                                                   ') where rubricRowID = 420
update seRubricRow set Title = rtrim('3.8: System of Intervention                                                                                                                                                               ') where rubricRowID = 421
update seRubricRow set Title = rtrim('3.9: Sensitivity to Diversity                                                                                                                                                             ') where rubricRowID = 422