//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSIntegrationLib.OSPIEntityLookupService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/Organization")]
    [System.SerializableAttribute()]
    public partial class Organization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRelationship", Namespace="http://schemas.datacontract.org/2004/07/Organization")]
    [System.SerializableAttribute()]
    public partial class OrganizationRelationship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationOSPILegacyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentOrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentOrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentOrganizationOSPILegacyCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationOSPILegacyCode {
            get {
                return this.OrganizationOSPILegacyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationOSPILegacyCodeField, value) != true)) {
                    this.OrganizationOSPILegacyCodeField = value;
                    this.RaisePropertyChanged("OrganizationOSPILegacyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentOrganizationId {
            get {
                return this.ParentOrganizationIdField;
            }
            set {
                if ((this.ParentOrganizationIdField.Equals(value) != true)) {
                    this.ParentOrganizationIdField = value;
                    this.RaisePropertyChanged("ParentOrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentOrganizationName {
            get {
                return this.ParentOrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentOrganizationNameField, value) != true)) {
                    this.ParentOrganizationNameField = value;
                    this.RaisePropertyChanged("ParentOrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentOrganizationOSPILegacyCode {
            get {
                return this.ParentOrganizationOSPILegacyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentOrganizationOSPILegacyCodeField, value) != true)) {
                    this.ParentOrganizationOSPILegacyCodeField = value;
                    this.RaisePropertyChanged("ParentOrganizationOSPILegacyCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OSPIEntityLookupService.IOrganizationService")]
    public interface IOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationService/GetOrganizationByCategoryTypeId", ReplyAction="http://tempuri.org/IOrganizationService/GetOrganizationByCategoryTypeIdResponse")]
        EDSIntegrationLib.OSPIEntityLookupService.Organization[] GetOrganizationByCategoryTypeId(int organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationService/GetOrganizationWithParentByCategoryTypeId" +
            "", ReplyAction="http://tempuri.org/IOrganizationService/GetOrganizationWithParentByCategoryTypeId" +
            "Response")]
        EDSIntegrationLib.OSPIEntityLookupService.OrganizationRelationship[] GetOrganizationWithParentByCategoryTypeId(int organizationTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationService/GetOrganizationRelationshipByOSPILegacyCo" +
            "de", ReplyAction="http://tempuri.org/IOrganizationService/GetOrganizationRelationshipByOSPILegacyCo" +
            "deResponse")]
        EDSIntegrationLib.OSPIEntityLookupService.OrganizationRelationship GetOrganizationRelationshipByOSPILegacyCode(string OSPILegacyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationServiceChannel : EDSIntegrationLib.OSPIEntityLookupService.IOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<EDSIntegrationLib.OSPIEntityLookupService.IOrganizationService>, EDSIntegrationLib.OSPIEntityLookupService.IOrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDSIntegrationLib.OSPIEntityLookupService.Organization[] GetOrganizationByCategoryTypeId(int organizationTypeId) {
            return base.Channel.GetOrganizationByCategoryTypeId(organizationTypeId);
        }
        
        public EDSIntegrationLib.OSPIEntityLookupService.OrganizationRelationship[] GetOrganizationWithParentByCategoryTypeId(int organizationTypeId) {
            return base.Channel.GetOrganizationWithParentByCategoryTypeId(organizationTypeId);
        }
        
        public EDSIntegrationLib.OSPIEntityLookupService.OrganizationRelationship GetOrganizationRelationshipByOSPILegacyCode(string OSPILegacyCode) {
            return base.Channel.GetOrganizationRelationshipByOSPILegacyCode(OSPILegacyCode);
        }
    }
}
